<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_First NameFirst NameFirst Name is requ_5ec857</name>
   <tag></tag>
   <elementGuidId>efb5b163-334e-4f41-829b-3e77586a799e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.makeStyles-form-23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@action='#']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>79573f91-a5be-4d85-b1e0-7b442d62a59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1125a33b-018d-42bf-8b36-99157b4d5748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>makeStyles-form-23</value>
      <webElementGuid>929b1d5f-db04-47e1-9499-ea91064dd967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First Name *First Name *First Name is requiredLast Name *Last Name *Username *Username *Password *Password *Confirm Password *Confirm Password *Sign UpHave an account? Sign In</value>
      <webElementGuid>1528d521-347e-4c3a-b717-00e567bf1538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;makeStyles-root-1&quot;]/main[@class=&quot;MuiContainer-root MuiContainer-maxWidthXs&quot;]/div[@class=&quot;makeStyles-paper-21&quot;]/form[@class=&quot;makeStyles-form-23&quot;]</value>
      <webElementGuid>09feffcb-923b-4bc8-858c-f218638d1299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='#']</value>
      <webElementGuid>94e5f893-f293-4cea-99cb-50e01d8bef28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/form</value>
      <webElementGuid>e6544b05-6cd5-4c4f-aa7b-4c498599e5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::form[1]</value>
      <webElementGuid>7ceaefcc-5172-4f45-8fbe-dc476d3f3439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>53b27dac-e602-4a24-bef3-6d60027aa64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'First Name *First Name *First Name is requiredLast Name *Last Name *Username *Username *Password *Password *Confirm Password *Confirm Password *Sign UpHave an account? Sign In' or . = 'First Name *First Name *First Name is requiredLast Name *Last Name *Username *Username *Password *Password *Confirm Password *Confirm Password *Sign UpHave an account? Sign In')]</value>
      <webElementGuid>e0d46787-460c-4244-8ff2-e1808235bb65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
