<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input131val-field_2.1.0--input</name>
   <tag></tag>
   <elementGuidId>6bd07c81-ca31-4e9b-a94a-24f0443e1df3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Subject' and @placeholder = 'Subject']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@aria-label = 'Subject' and @placeholder = 'Subject']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb5e1e17-0cfc-47cd-985b-4f5b79206ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-garden-id</name>
      <type>Main</type>
      <value>forms.input</value>
      <webElementGuid>4317a17a-f60c-4120-ad9f-9c617c35bb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-garden-version</name>
      <type>Main</type>
      <value>8.73.2</value>
      <webElementGuid>28ed2b7b-5a0e-4277-b05a-b6e83ef8cb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f870be4-65c1-4c38-a865-61bec97f6222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>131val-field_2.1.0--input</value>
      <webElementGuid>afef2974-2e17-470e-8693-fcf694bb95f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>131val-field_2.1.0--label</value>
      <webElementGuid>b7b30572-ad1a-4da9-80b4-c30c78ef9e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>omni-header-subject</value>
      <webElementGuid>9858037f-0be9-4dad-a6ce-64c1c120a98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>a0c93197-52ff-48b4-a13b-ea0dcad5f6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>50b63e5b-3c3b-432a-bc0a-3cca2f646443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1nvv38f-6 UvLUD StyledTextInput-sc-k12n8x-0 bXXlCE</value>
      <webElementGuid>b3b4b51b-60c8-4d93-89d6-57faaeb14434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;131val-field_2.1.0--input&quot;)</value>
      <webElementGuid>ebe650d9-dd90-4912-8d1c-206e069f230d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='131val-field_2.1.0--input']</value>
      <webElementGuid>6bfe6d5d-37b5-4d55-b48c-4569a90851b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember3002']/div/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>04f5a04e-69ae-4a77-b6df-b5503e957caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>d44d63fc-0a80-42e5-8cf2-087f06964b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '131val-field_2.1.0--input' and @placeholder = 'Subject']</value>
      <webElementGuid>ede1e6a6-aced-495f-bfde-b331b36a0cd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
