<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JiraTestSuite1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>pravin.raveendran@katalon.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>bcc1fdb2-da12-45a6-a98a-533c5824430f</testSuiteGuid>
   <testCaseLink>
      <guid>6c1c6992-ff0c-42aa-aa6f-faa41d78da82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JiraTests/IN-7 Story21</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1f37805d-9522-452f-b922-fd7117e4139d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ContactDetails-SIT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7358eba2-52e4-44f1-8293-c97632b51dae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>684bd2fd-81ea-4f1c-8036-4585f044e4e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cdb582e-94b7-4d9c-8e0e-0df12dea4c6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a1f995d-26a8-4862-8479-adca1209ec3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e92aeb2-3761-4aed-9a3d-4e19f3c54a47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28735b0c-f9bb-4aef-8abf-a4b8b4ab7132</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3cc3327-fb89-4e81-b48d-59928206944b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08e8a612-98ec-426f-af1b-85de55c80215</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9502dfb-495e-4465-93bd-82135ede5aba</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
