<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MaybankSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>shahiman.sharom@maybank.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1af6a58e-0df8-42b7-b5fe-ab6d2a347007</testSuiteGuid>
   <testCaseLink>
      <guid>64c1a589-3771-4364-bfaa-dd26dd9f2bf0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebTestCases/MayBankTradeWebUI</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>dc79bdc1-61b9-48e2-9452-040c63dcba6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/APITests/REST/Rest</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>096a63e5-7534-4e8e-91bc-69439585cb7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db926443-b7ee-426d-9083-5d3bbf0c32fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cc7fd1a-f6f2-492c-a9af-1298b7e7fb89</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
