<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>WebTestSuite1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>pravinrajpaul@gmail.com;pravin.raveendran@katalon.com;</mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ec3f61a3-67f0-4b3a-8d5c-3ce11dcaa5bd</testSuiteGuid>
   <testCaseLink>
      <guid>4a27df78-254c-4b94-be3f-31bde6e91236</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebTestCases/WebTestCase1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7358eba2-52e4-44f1-8293-c97632b51dae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>684bd2fd-81ea-4f1c-8036-4585f044e4e4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
