<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accept</name>
   <tag></tag>
   <elementGuidId>7f8e313e-5fa8-45b7-bfc5-4b6614718e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptCookie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='acceptCookie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>754b79c8-ed29-4aee-a5ae-84f7f08bddc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptCookie</value>
      <webElementGuid>76f2c29e-059b-4d73-9b50-890a00d2ff2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6966dca1-044f-4d57-8e7f-a9bee98eb2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary small</value>
      <webElementGuid>92b997c1-26e8-446d-a0ea-ca4e1d1e5991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>ecd7a4af-e05c-4cd9-aab4-d49890dcf2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptCookie&quot;)</value>
      <webElementGuid>3b5339cb-c5df-435e-a83c-1f56f01d9f76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='acceptCookie']</value>
      <webElementGuid>ac87d5df-2ede-48c4-a3ab-63d24d85dd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookies']/div/div/div[2]/p/a[2]</value>
      <webElementGuid>068def3e-e186-47d9-bb7e-5654243657f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Accept')]</value>
      <webElementGuid>5bd1e922-92aa-4ac9-b28a-23556c2cb478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Information'])[1]/following::a[1]</value>
      <webElementGuid>670ff3ff-d968-4763-afe5-32067359a382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © NEC Corporation of America 2023. All rights reserved.'])[1]/following::a[7]</value>
      <webElementGuid>601d350c-47d3-4731-a877-125296449c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose country or region'])[1]/preceding::a[1]</value>
      <webElementGuid>928b673e-5d08-436a-939b-3dc6be6408e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/preceding::a[1]</value>
      <webElementGuid>4903892a-e70e-4800-b5e3-135154f47d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept']/parent::*</value>
      <webElementGuid>21468ce6-88da-49b5-b7ec-90688fa4d3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>378bf4f7-bb7f-4d59-9a8e-bd89183bdfb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/p/a[2]</value>
      <webElementGuid>5e7dfa38-8a5b-4cc2-935d-2b85c3550012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'acceptCookie' and @href = '#' and (text() = 'Accept' or . = 'Accept')]</value>
      <webElementGuid>3b866440-55fd-4ae3-8784-0ee9b1274a3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
