<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Helpdesk</name>
   <tag></tag>
   <elementGuidId>52014560-10d2-4c56-a894-f61a0d427a6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solution-page-menu']/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9961a6d0-d08c-41dd-8d40-b5109defb31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cloud-services/extend/helpdesk/</value>
      <webElementGuid>0e54f179-eb6c-4615-8f02-1bf9a51f6417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Helpdesk</value>
      <webElementGuid>69f61f0f-3ef9-4025-911e-debfd1432772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solution-page-menu&quot;)/ul[@class=&quot;menu vertical medium-horizontal&quot;]/li[3]/a[1]</value>
      <webElementGuid>46387b05-f99d-473b-9c0a-ad9941883179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solution-page-menu']/ul/li[3]/a</value>
      <webElementGuid>66d72e1d-363c-46b1-81a1-291e6786e64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Helpdesk')]</value>
      <webElementGuid>57992629-cbda-4a65-a827-83c389d5b96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CRM'])[1]/following::a[1]</value>
      <webElementGuid>8b05d18a-9c6f-443f-a028-76fdae717e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API platform'])[1]/following::a[2]</value>
      <webElementGuid>2307afed-5338-4eb5-8770-8762320099bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Productivity'])[1]/preceding::a[1]</value>
      <webElementGuid>11e4a4f8-e1a0-49bf-a251-f16080c7b544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Center'])[1]/preceding::a[2]</value>
      <webElementGuid>7a3b6639-e1d9-47a6-8ce2-e9889c27007e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Helpdesk']/parent::*</value>
      <webElementGuid>a5edf8f8-38e3-42b1-ab2b-d1cb67915595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cloud-services/extend/helpdesk/')]</value>
      <webElementGuid>dc901845-f11d-4d57-832e-ab0a42129e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>d4e71707-41dd-4894-889f-19919a39f209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cloud-services/extend/helpdesk/' and (text() = 'Helpdesk' or . = 'Helpdesk')]</value>
      <webElementGuid>16a0fed3-9ef8-40a1-97ff-24529eacc969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
