<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Helpdesk</name>
   <tag></tag>
   <elementGuidId>52014560-10d2-4c56-a894-f61a0d427a6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solution-page-menu']/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cba4f7a2-935d-482a-8396-805791fc2690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cloud-services/extend/helpdesk/</value>
      <webElementGuid>80d2ba55-47a3-4766-a004-f5005d6ab39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Helpdesk</value>
      <webElementGuid>e371295a-764c-4abe-82d0-2d71ea2d9171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solution-page-menu&quot;)/ul[@class=&quot;menu vertical medium-horizontal&quot;]/li[3]/a[1]</value>
      <webElementGuid>df16fcf4-4bf3-42a5-b615-a6c45a432a7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solution-page-menu']/ul/li[3]/a</value>
      <webElementGuid>031124c1-9ea4-4f01-886f-3342cf0ad56c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Helpdesk')]</value>
      <webElementGuid>d1a0efef-2f5b-4563-8039-0535093be6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CRM'])[1]/following::a[1]</value>
      <webElementGuid>8baf8d27-9a4b-40e8-b08b-07c5ba24dc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API platform'])[1]/following::a[2]</value>
      <webElementGuid>07d564da-8aba-474e-ac2c-6579f8e7c9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Productivity'])[1]/preceding::a[1]</value>
      <webElementGuid>9cd2b8f9-837a-452e-8d4b-2b6264e50a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Center'])[1]/preceding::a[2]</value>
      <webElementGuid>6d51b4c2-17ff-4bd5-95f5-38ee8cfba26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Helpdesk']/parent::*</value>
      <webElementGuid>91fb46b4-b5e7-4d9e-a5a4-cecd59efe69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cloud-services/extend/helpdesk/')]</value>
      <webElementGuid>26360dd8-0f91-469e-ab94-07834144f5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>8c5d04b0-4ac4-4cbd-85e9-1f4a6478bcc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cloud-services/extend/helpdesk/' and (text() = 'Helpdesk' or . = 'Helpdesk')]</value>
      <webElementGuid>4908034d-b2c6-48e1-9b1f-9d5d13a55a30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
