<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1_2</name>
   <tag></tag>
   <elementGuidId>8d98c00a-db51-4576-b3b1-52dbfe0eeb9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[2]/div/div/div/div/div/button/span[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a81de62c-5fbd-4aec-821e-6925a368df85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;sticky-subnavigation has-scrolled&quot;]/div[@class=&quot;navigation-wrapper&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;grid-x grid-padding-x align-middle small-padding-collapse&quot;]/div[@class=&quot;cell small-12 medium-auto extend-type&quot;]/div[1]/button[@class=&quot;toggle-navigation float-right&quot;]/span[4]</value>
      <webElementGuid>1d0b210b-4302-4d3a-9b56-95ee4890b9fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div/div/div/div/div/button/span[4]</value>
      <webElementGuid>6cf75b27-b626-4d7c-8f70-f0138a3170ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span[4]</value>
      <webElementGuid>0ea2cd5e-d199-4131-8f00-0c9efddd7b20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
