<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1_2_3</name>
   <tag></tag>
   <elementGuidId>93711b41-57f3-4cff-a825-cc6a41a6e164</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[2]/div/div/div/div/div/button/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>24103294-fd4a-4e58-976e-252896c35ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;sticky-subnavigation has-scrolled&quot;]/div[@class=&quot;navigation-wrapper&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;grid-x grid-padding-x align-middle small-padding-collapse&quot;]/div[@class=&quot;cell small-12 medium-auto extend-type&quot;]/div[1]/button[@class=&quot;toggle-navigation float-right open&quot;]/span[3]</value>
      <webElementGuid>d31d2fea-0593-4594-a9ee-bc7552222554</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div/div/div/div/div/button/span[3]</value>
      <webElementGuid>6d604ab5-e069-4935-b870-d5be8558b9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span[3]</value>
      <webElementGuid>da9c2049-516c-4fd3-9622-10a251f05692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
