<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Great for teens_svelte-18nliqd multi-check</name>
   <tag></tag>
   <elementGuidId>055ae17f-379b-426c-889a-3d35d597db2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.grid-y.choosable.svelte-18nliqd.ctracking > div.cell.align-self-top.text-right.svelte-18nliqd > div.circle.svelte-18nliqd.multi-select > div.svelte-18nliqd.multi-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kit-4g-oil-control-duo']/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b587243-3fa3-494d-bea6-c63ec6dd72b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svelte-18nliqd multi-check</value>
      <webElementGuid>3bc792f2-fb6e-4f66-bc69-c4920683d9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kit-4g-oil-control-duo&quot;)/div[@class=&quot;grid-y choosable svelte-18nliqd ctracking&quot;]/div[@class=&quot;cell align-self-top text-right svelte-18nliqd&quot;]/div[@class=&quot;circle svelte-18nliqd multi-select&quot;]/div[@class=&quot;svelte-18nliqd multi-check&quot;]</value>
      <webElementGuid>5adf2e9b-db81-4b6b-9e2c-662082fbd655</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kit-4g-oil-control-duo']/div/div[2]/div/div</value>
      <webElementGuid>018a4f7b-a7fb-4f2b-9beb-54fb27d8beef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>db00f003-30ae-4a66-a0e0-d5d8f1c85002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
