<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your subscription Renews every 90 days _0667a0</name>
   <tag></tag>
   <elementGuidId>3364f3c7-bee8-4d2a-88da-d179634f6bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cell.summary.auto.align-self-middle.svelte-qhqfzs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tpc-sas']/main/div/div[5]/div[2]/div/div/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98d6d356-d291-4ef4-acac-58741f8005d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell summary auto align-self-middle svelte-qhqfzs</value>
      <webElementGuid>ffea7fdc-712a-43c9-94f4-07a20706a747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your subscription Renews every 90 days and billed monthly. (3 monthly installments of $34.95 )  Proactiv+® 3-Step Routine $24.95  Mark &amp; Scar Duo +$10.00    Pore Cleansing Brush $46.75 $0.00 Shipping Free  Today’s total $34.95</value>
      <webElementGuid>94827e16-e57c-4921-a496-110cf3f5df7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tpc-sas&quot;)/main[@class=&quot;svelte-139nppl&quot;]/div[@class=&quot;grid-x svelte-1jmohgr&quot;]/div[@class=&quot;cell svelte-1jmohgr small-order-4&quot;]/div[@class=&quot;grid-x pane svelte-1jmohgr&quot;]/div[@class=&quot;cell finalize svelte-1jmohgr&quot;]/div[@class=&quot;grid-x align-self-middle svelte-1jmohgr large-up-1&quot;]/div[@class=&quot;cell small-12 medium-5 large-7 xxlarge-6 align-self-middle svelte-1jmohgr medium-12&quot;]/div[@class=&quot;grid-x svelte-1jmohgr&quot;]/div[@class=&quot;cell align-self-middle svelte-1jmohgr&quot;]/div[@class=&quot;grid-x panel svelte-qhqfzs&quot;]/div[@class=&quot;cell summary auto align-self-middle svelte-qhqfzs&quot;]</value>
      <webElementGuid>6192f0a0-1a38-4731-8875-339c8e333592</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-sas']/main/div/div[5]/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>f62f263d-b709-44f4-ad00-ed409d79fdaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More details'])[7]/following::div[11]</value>
      <webElementGuid>ee1d2f9d-fa36-4ea9-9452-5530c66f250c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$46.75'])[1]/following::div[13]</value>
      <webElementGuid>31613325-3d01-45bc-8ae6-62468f962a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>4a4d1ef4-5d00-4316-91c6-4b7d9de0b871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your subscription Renews every 90 days and billed monthly. (3 monthly installments of $34.95 )  Proactiv+® 3-Step Routine $24.95  Mark &amp; Scar Duo +$10.00    Pore Cleansing Brush $46.75 $0.00 Shipping Free  Today’s total $34.95' or . = 'Your subscription Renews every 90 days and billed monthly. (3 monthly installments of $34.95 )  Proactiv+® 3-Step Routine $24.95  Mark &amp; Scar Duo +$10.00    Pore Cleansing Brush $46.75 $0.00 Shipping Free  Today’s total $34.95')]</value>
      <webElementGuid>9ea93a28-fb38-407c-b5b2-e31eb7af0d92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
