<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Improves skin tone_svelte-18nliqd multi-check</name>
   <tag></tag>
   <elementGuidId>dd42dd47-95b9-4c3b-a89a-9f2c58a689e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.svelte-18nliqd.multi-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kit-4g-mark-scar-duo']/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3047f7b-735a-4b01-84c5-650d7afe223b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svelte-18nliqd multi-check</value>
      <webElementGuid>c05f877b-c75d-4eba-8c01-b7b0efad81f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kit-4g-mark-scar-duo&quot;)/div[@class=&quot;grid-y choosable svelte-18nliqd chosen&quot;]/div[@class=&quot;cell align-self-top text-right svelte-18nliqd&quot;]/div[@class=&quot;circle svelte-18nliqd multi-select&quot;]/div[@class=&quot;svelte-18nliqd multi-check&quot;]</value>
      <webElementGuid>f5218a80-f607-4838-92a6-9f8ef23685f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kit-4g-mark-scar-duo']/div/div[2]/div/div</value>
      <webElementGuid>36c41c0d-f1aa-4e2f-92ac-3135e85512f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div[2]/div/div</value>
      <webElementGuid>3aca7cc6-87f1-4161-89d0-e6bfb40641cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
