<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_46.75_w20 text-right align-self-middle _29eaaa</name>
   <tag></tag>
   <elementGuidId>28f84bee-8027-4e34-858b-ee78b21dee68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w20.text-right.align-self-middle.svelte-1d6nfs6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sas-checkout']/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a8595d8-607c-4951-ba79-e2d58d7a9ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w20 text-right align-self-middle svelte-1d6nfs6</value>
      <webElementGuid>81be6b6f-855c-41d6-a201-e02c046d00b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sas-checkout&quot;)/div[@class=&quot;w20 text-right align-self-middle svelte-1d6nfs6&quot;]</value>
      <webElementGuid>3f6dfa15-5f0a-4870-8ee6-34c61b0dc4bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sas-checkout']/div[3]</value>
      <webElementGuid>7b9dfce6-e29e-41d7-aaf7-ef137d03eb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$46.75'])[2]/following::div[14]</value>
      <webElementGuid>07043229-c93b-4272-8fb4-45278ff684ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+$10.00'])[1]/following::div[19]</value>
      <webElementGuid>2c466fbc-6aeb-4676-b125-3c321158725e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/preceding::div[3]</value>
      <webElementGuid>86a6632b-2b7b-4793-97c7-b8008d5eb116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::div[4]</value>
      <webElementGuid>62d60123-72b8-434f-9d04-2e2b7134b99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[3]</value>
      <webElementGuid>62e5d7cf-5d53-408a-8b94-f85cfde21899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
