<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome to Jenkins_j_password</name>
   <tag></tag>
   <elementGuidId>e4ede5a0-2547-4cbe-9d1d-5059d70c44fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='j_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;j_password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b5b57cf-276f-4c05-be6d-72c85f14446c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_password</value>
      <webElementGuid>54d7420d-971a-46b5-b7a1-a520bbda5539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>323d311f-95fb-40c8-ab83-535b75477f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0141e6aa-e4ed-4459-95dd-341eaed1091e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jenkins-input normal</value>
      <webElementGuid>172bcae3-7de1-4474-b0aa-405d550bc51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>d2cfab8b-67bd-4e82-b4b8-7d73b6db71e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;simple-page&quot;]/div[@class=&quot;modal login&quot;]/form[1]/div[@class=&quot;jenkins-form-item jenkins-form-item--tight&quot;]/input[@class=&quot;jenkins-input normal&quot;]</value>
      <webElementGuid>4cafc4e4-6d21-4ae4-a7a7-f3dada2ed4ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='j_password']</value>
      <webElementGuid>b7cea8d8-96ea-4147-b17e-bdf71332541c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>255bdd3b-55f4-4e05-a15f-2d328fa93815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'j_password' and @placeholder = 'Password' and @type = 'password']</value>
      <webElementGuid>39c408ae-4c7d-451c-a79b-80817c31b5fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
