<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add</name>
   <tag></tag>
   <elementGuidId>e1ddff03-4037-4338-9611-9c13f46fb816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.LRf.LRg.LRh.LRi.LRb.LRj.LRk.LRl.LRm.LRn.LRo.LRp.LRq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ccb1783-a61e-4503-891c-eaf2e9447fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>header-toolbar-add-menu-button</value>
      <webElementGuid>e1687641-15d0-431a-a751-ab40b6628ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5aa8cf7-7e43-47d3-8a97-a0bb88704b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>730fa00e-2dab-43a7-8f4c-1312694d8ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>89a9d7fd-9fd8-48d4-905d-ce2663f947ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b9f50f1f-2d02-44d3-a1dd-93e7ac60c34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LRf LRg LRh LRi LRb LRj LRk LRl LRm LRn LRo LRp LRq</value>
      <webElementGuid>42aec46b-26a9-44bc-bb4b-be3bff8209a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>downshift-0-menu</value>
      <webElementGuid>66d69e05-2577-4a2e-b6af-0e63d2c14901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>a375f8b4-0783-427e-adb0-b92f34ec263c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember1523&quot;)/div[@class=&quot;LRa LRb LRc LRd LRe&quot;]/div[@class=&quot;sc-9os9l3-0 kdmWFW&quot;]/div[@class=&quot;sc-1p2x6t1-0 kztInl&quot;]/div[@class=&quot;sc-19uji9v-0 jFxgwS&quot;]/button[@class=&quot;LRf LRg LRh LRi LRb LRj LRk LRl LRm LRn LRo LRp LRq&quot;]</value>
      <webElementGuid>9be90543-2f7d-488e-9bb6-dc53ec9379f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>00a988fa-bdff-4972-8c21-e2023e29ed5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember1523']/div/div/div/div/button</value>
      <webElementGuid>733fa031-675c-45c6-bc18-5ab3c8f0411f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>54c11451-53f5-4e22-97a2-09bc8c24825d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'add' or . = 'add')]</value>
      <webElementGuid>07a8dd0f-16c9-41de-a781-5a1abb6e4bb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
