<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Ticket</name>
   <tag></tag>
   <elementGuidId>4e673d11-bccc-4f4e-9be8-17c0a9258b82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#downshift-0-item-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='downshift-0-item-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>091e0151-0cac-4b30-a984-6c7c271098a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-garden-id</name>
      <type>Main</type>
      <value>dropdowns.item</value>
      <webElementGuid>3d810082-d9c7-40f5-bff1-09da413f763b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-garden-version</name>
      <type>Main</type>
      <value>8.54.3</value>
      <webElementGuid>a9f059a6-3f01-41f5-8272-de82a85e130d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downshift-0-item-0</value>
      <webElementGuid>8355501b-1928-41c2-8436-be708b630e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>5f0b31b0-7d2c-4184-9677-90e3925017dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-type</name>
      <type>Main</type>
      <value>ticket</value>
      <webElementGuid>1dfd14ad-f138-4a16-8dd3-d22857b36cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>header-toolbar-add-menu-new-ticket</value>
      <webElementGuid>575da750-75d2-4762-bb70-13feaaa57fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-k9fyge-0 kjKwzb StyledItem-sc-1xeog7q-0 hXnYsP</value>
      <webElementGuid>0ed179b6-4fa3-49f3-9f6d-d75937e6d7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ticket</value>
      <webElementGuid>c7bee2b6-bc46-4628-990b-ff53890bf34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-0-item-0&quot;)</value>
      <webElementGuid>b9bc840d-32bc-4110-a7a9-083dd0978d0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='downshift-0-item-0']</value>
      <webElementGuid>c72ecd00-8d1d-4e6e-8983-0c0dd8a971b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='downshift-0-menu']/li[3]</value>
      <webElementGuid>ebe73fcf-0bea-4d6c-b504-d2d170664cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>3e4cbe5e-3b51-4a92-a22c-e63ac23a2f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'downshift-0-item-0' and (text() = 'Ticket' or . = 'Ticket')]</value>
      <webElementGuid>1cb77c31-4053-417d-9a9a-53dfee3d1cd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
