<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noOfTickets</name>
   <tag></tag>
   <elementGuidId>43b2d352-b714-422c-b315-c8eb9ca532d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[data-test-id=&quot;views_views-header-counter&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
