<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input131val-field_2.1.0--input</name>
   <tag></tag>
   <elementGuidId>ed2ec5a8-e681-4ac4-a051-9d3517f0868b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='131val-field_2.1.0--input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc5f6e34-c147-4542-b36b-75a1cf15bb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-garden-id</name>
      <type>Main</type>
      <value>forms.input</value>
      <webElementGuid>8fd96565-035a-425b-970f-0f7853ab107d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-garden-version</name>
      <type>Main</type>
      <value>8.73.2</value>
      <webElementGuid>64cb1506-46dd-40c3-869a-b082bfe63215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3fe25237-4cae-45b6-bb49-245876f940ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>131val-field_2.1.0--input</value>
      <webElementGuid>abb94383-18dc-46de-ad09-daf152dd2da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>131val-field_2.1.0--label</value>
      <webElementGuid>588a2a7d-d0f4-4179-a14b-8057a7c91738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>omni-header-subject</value>
      <webElementGuid>2ca59a85-086e-4712-83f0-9cd25aa82048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>b2e5ed0b-e1a5-4b78-9897-535e7449b6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>b46dc778-d450-4647-b1b8-186b09cf7b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1nvv38f-6 UvLUD StyledTextInput-sc-k12n8x-0 bXXlCE garden-focus-visible</value>
      <webElementGuid>13935a6f-8848-4526-b1b0-8f86e1eca935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Subject Tex</value>
      <webElementGuid>e1a52d40-6cd7-47d0-a939-ad591c62ee0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-garden-focus-visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0bdf030-b987-49b5-89ee-47ecee4b6ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;131val-field_2.1.0--input&quot;)</value>
      <webElementGuid>0ec9433b-286e-4262-b077-8c04696a4496</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='131val-field_2.1.0--input']</value>
      <webElementGuid>e2d684de-68ab-4890-b784-1ce693209190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember3002']/div/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>baa8f08a-3727-43ea-ab12-497894b79a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>f67dbc09-788d-43d1-ad92-9a91f76974ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '131val-field_2.1.0--input' and @placeholder = 'Subject']</value>
      <webElementGuid>8aa89ad9-76ed-4153-8955-4053be67ed44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
