<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Helpdesk</name>
   <tag></tag>
   <elementGuidId>843ab6e1-afd0-4bd8-8e53-e01d90fefbb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solution-page-menu']/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.menu.vertical.medium-horizontal > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4eadb9f-43dc-445c-868a-d4a8d15ffb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cloud-services/extend/helpdesk/</value>
      <webElementGuid>c5a37441-348f-457e-a3f1-75f39e240e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Helpdesk</value>
      <webElementGuid>27885aa5-0b78-4844-a1f3-79ed77c854ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solution-page-menu&quot;)/ul[@class=&quot;menu vertical medium-horizontal&quot;]/li[3]/a[1]</value>
      <webElementGuid>506f7829-9df1-40cf-af89-a38e3c1c38db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solution-page-menu']/ul/li[3]/a</value>
      <webElementGuid>0155fb78-a4a2-4da8-a7ec-d2c487aea5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Helpdesk')]</value>
      <webElementGuid>39984875-880a-474a-bd1e-161e4e34ff01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CRM'])[1]/following::a[1]</value>
      <webElementGuid>5fa0be5b-0734-4569-81b8-5e38eae4e89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API platform'])[1]/following::a[2]</value>
      <webElementGuid>dd2be414-180d-41cb-bf03-10cfeb35ca61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Productivity'])[1]/preceding::a[1]</value>
      <webElementGuid>ca0a2e06-1b11-4dd1-8504-40aab558c56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Center'])[1]/preceding::a[2]</value>
      <webElementGuid>20eca61b-b0e7-4a2f-91af-f7c3cecc27b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Helpdesk']/parent::*</value>
      <webElementGuid>84ca51a0-5c08-4425-89a0-e24090e226ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cloud-services/extend/helpdesk/')]</value>
      <webElementGuid>36247adf-cdd7-4929-a0e6-2e4c45566bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>fa233431-e9dc-4479-8f02-24f615438f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cloud-services/extend/helpdesk/' and (text() = 'Helpdesk' or . = 'Helpdesk')]</value>
      <webElementGuid>78fe1a93-07bf-4bfe-9cb0-e0138176a13e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
