<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Productivity</name>
   <tag></tag>
   <elementGuidId>f06715ae-9b95-4710-b6bd-6f23c0028252</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solution-page-menu']/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.menu.vertical.medium-horizontal > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9198f185-59ba-49d1-873f-d01340f8c290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cloud-services/extend/productivity/</value>
      <webElementGuid>78bad809-f0eb-411f-89b1-832b3c6679df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Productivity</value>
      <webElementGuid>33264518-3dd0-4211-83f0-606b6438bf66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solution-page-menu&quot;)/ul[@class=&quot;menu vertical medium-horizontal&quot;]/li[4]/a[1]</value>
      <webElementGuid>7481f2e1-2b74-4b61-8e78-211a964310aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solution-page-menu']/ul/li[4]/a</value>
      <webElementGuid>dce6ae8c-59e0-42ee-a9b8-024c430caab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Productivity')]</value>
      <webElementGuid>8b8d7128-380c-4bf9-a19f-772f6d9dc12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Helpdesk'])[1]/following::a[1]</value>
      <webElementGuid>6ca82c50-aab1-4530-8de9-1f18f43dd908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CRM'])[1]/following::a[2]</value>
      <webElementGuid>fb7a15b3-1e66-4bfc-99e1-c677afc306e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Center'])[1]/preceding::a[1]</value>
      <webElementGuid>212c95a8-0a84-43f8-a7d9-f36d600ebe22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::a[2]</value>
      <webElementGuid>d62a5525-04eb-40f9-ab6f-3802109c3d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Productivity']/parent::*</value>
      <webElementGuid>6706f48c-12f9-4e48-bdc0-1e5b7d3860e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cloud-services/extend/productivity/')]</value>
      <webElementGuid>5ed1cc38-30ad-47cc-912b-080f3679a7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/ul/li[4]/a</value>
      <webElementGuid>61d5c02b-4cbb-4dac-ae6f-ea5153d1568f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cloud-services/extend/productivity/' and (text() = 'Productivity' or . = 'Productivity')]</value>
      <webElementGuid>6facf7f5-e05b-4618-b460-4719ca01753c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
