<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Account_acct</name>
   <tag></tag>
   <elementGuidId>c462bb2f-1e58-4a05-a635-30c561fb2686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='ui-ordent-slc-acct']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-ordent-slc-acct</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>851dafa3-9d7b-499d-84fe-e1b32081e0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-ordent-slc-acct</value>
      <webElementGuid>d2aa5aab-ef63-42db-9714-6fdd34248f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acct</value>
      <webElementGuid>424b6ec8-2fea-4801-88f0-5a463f81fd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divStkQteWnd&quot;)/div[@class=&quot;ui-om-ordent ui-draggable ui-draggable-handle&quot;]/div[@class=&quot;ui-om-ordent-b&quot;]/div[@class=&quot;ui-ordent-cntnr_t&quot;]/div[@class=&quot;ui-ordent-cntnr_l&quot;]/div[1]/div[@class=&quot;ui-ordent-slc-acct&quot;]</value>
      <webElementGuid>661dd2e8-0a26-4dcd-af9b-964cceaf289a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframeifrm</value>
      <webElementGuid>6add7b53-7f36-4682-bd1f-e014358c4238</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='acct']</value>
      <webElementGuid>c5f8b439-a66c-40a6-bf0d-88c00b008be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divStkQteWnd']/div[5]/div[2]/div/div/div/div</value>
      <webElementGuid>23d7bef7-e10e-4c10-929f-59d36c6fc51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account:'])[1]//div[1]</value>
      <webElementGuid>6757cb2b-6205-45a4-a7b5-73b5d514110c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty: x100'])[1]/preceding::div[1]</value>
      <webElementGuid>74f2fda2-fa08-4701-923a-8b4a591dbd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price: MYR'])[1]/preceding::div[2]</value>
      <webElementGuid>3fc199d9-e6a8-4516-9de2-abf030a8f959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div</value>
      <webElementGuid>08536704-66c9-48df-bb87-7b6f9c3fd8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'acct']</value>
      <webElementGuid>369798fc-684a-40e8-94b0-dc792c8a11c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
