<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ADD00044- HEE LEE CHAN</name>
   <tag></tag>
   <elementGuidId>3f046aa5-fbf1-47a1-a49d-7642895e1382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divClntOpt']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.selected</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>656466b4-0327-4ac3-8591-6953caae5360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iidx</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aefe4e71-7481-4978-b345-5f3c3cc77c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clntid</name>
      <type>Main</type>
      <value>ADD00044</value>
      <webElementGuid>b9ff5084-5473-491f-85c3-d2d3312d29ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clntnm</name>
      <type>Main</type>
      <value>HEE LEE CHAN</value>
      <webElementGuid>8a6782fc-23f6-46f4-93bf-002e64996110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clntcdsno</name>
      <type>Main</type>
      <value>021063037</value>
      <webElementGuid>fa3ec9b6-9e97-47b1-8490-3846c361ba62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>ad95ec7b-d412-4e5f-9692-2783ef28e5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ADD00044- HEE LEE CHAN</value>
      <webElementGuid>f475f351-d5c4-42b8-90da-6b440b926b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divClntOpt&quot;)/div[@class=&quot;selected&quot;]</value>
      <webElementGuid>557cb127-cc35-46a3-be1a-2b2a68091b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframeifrm</value>
      <webElementGuid>7f99e042-4570-4b30-ac7d-ea8b5bb370dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divClntOpt']/div</value>
      <webElementGuid>f112757c-62c5-47eb-91b9-7f2c72b322dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The transaction cost are estimated amount ONLY.'])[1]/following::div[3]</value>
      <webElementGuid>310045b9-7e61-4668-8c60-35121a7fdd31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note :'])[1]/following::div[3]</value>
      <webElementGuid>96ba70b9-d9b2-4cc3-9b15-f41853ff4aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div</value>
      <webElementGuid>30e0e188-263f-448b-92cf-efe422cbe5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' ADD00044- HEE LEE CHAN' or . = ' ADD00044- HEE LEE CHAN')]</value>
      <webElementGuid>cc92e4a3-5518-44bb-8771-a257e0fa9d91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
