<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Explore Global Trading_ifrMP</name>
   <tag></tag>
   <elementGuidId>c71480e6-0001-4b6a-b509-0956beda7380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifrMP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifrMP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>411dba3e-81af-4ac2-b9af-72870d314881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifrMP</value>
      <webElementGuid>45a3c47e-4219-4380-af52-8722e24168e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>csmsq_mp.aspx?Token=NjYwNzIzMTQ1MTI4fDF8NjYwNzIzMTQ1MTI4fDF8Mnw3NjI3NzI0Mg==</value>
      <webElementGuid>7b8a4a8c-6bb5-440c-9ed0-2cb32688564e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d9e7cd32-224c-4672-ab07-f015871a8bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>650</value>
      <webElementGuid>e1f318f3-71bc-4e83-87b1-73ec69a088bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>82a6eb66-5bea-46eb-9f48-30228ebb94ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mp show</value>
      <webElementGuid>f2747e45-c7da-415d-8552-1e5ea203d8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-popups allow-top-navigation allow-modals allow-forms allow-scripts allow-same-origin allow-popups-to-escape-sandbox</value>
      <webElementGuid>cf7758a4-1a79-4699-92c9-29a189cc52bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifrMP&quot;)</value>
      <webElementGuid>d1f32560-9aa3-4103-bcc3-0ab0c26197ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifrMP']</value>
      <webElementGuid>18480552-ee24-4625-a1fc-b7b6879a7a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_wrapper']/div/table/tbody/tr/td/iframe[2]</value>
      <webElementGuid>7d434122-b3b3-4049-94eb-a155a8917d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/iframe[2]</value>
      <webElementGuid>df6a1727-df69-4c8d-bb69-92f39711408b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifrMP' and @src = 'csmsq_mp.aspx?Token=NjYwNzIzMTQ1MTI4fDF8NjYwNzIzMTQ1MTI4fDF8Mnw3NjI3NzI0Mg==']</value>
      <webElementGuid>e18e003e-6cf5-4acd-9be9-ba99bd7abfc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
