<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframeifrm</name>
   <tag></tag>
   <elementGuidId>90bd67ae-8357-4ff5-a239-55847eb0c80c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifrm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifrm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3996c85d-169f-43af-b73f-3262f94f88b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../MIBWecosMP/csmsq.aspx</value>
      <webElementGuid>3612b7cb-623e-43f8-9fb1-8db7c9723fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifrm</value>
      <webElementGuid>a4e25f94-b595-44a5-8400-89033c8b103f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifrm&quot;)</value>
      <webElementGuid>5b068506-4b9a-410e-b7a6-4f6340f37fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframe_Explore Global Trading_ifrMP</value>
      <webElementGuid>a50beaf5-15ed-4e8a-8788-6801ede7dfe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifrm']</value>
      <webElementGuid>f657c280-44a8-4dff-968e-36d9b3013db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divContent']/iframe</value>
      <webElementGuid>c849a1c6-fbdc-4e03-917e-2d6869c881eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ba1d925e-121b-4d91-8114-365b48e511e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '../MIBWecosMP/csmsq.aspx' and @id = 'ifrm']</value>
      <webElementGuid>225fc9e3-b591-42fa-9fd6-fb9c1f94ca60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
