<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qty x100_txtQty</name>
   <tag></tag>
   <elementGuidId>0798b8c9-3062-4fae-8118-824474bb7625</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtQty']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtQty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24284a33-48fb-4d8d-84fd-9b3bf0be75e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtQty</value>
      <webElementGuid>7e03576c-5a0a-46e8-b535-94e7e1d29de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09e8a487-709b-4b9f-862b-535168fd5db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>7069bfe1-3ba5-4f85-9d0f-f4f7a9e2305f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtQty&quot;)</value>
      <webElementGuid>76b56229-cac3-4b86-91a9-7da74a46fd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframeifrm</value>
      <webElementGuid>779024e0-4202-4832-90c9-468fc288e124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtQty']</value>
      <webElementGuid>85d95c39-cef7-43bd-bb85-276bc19d27d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divStkQteWnd']/div[5]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>851ed814-9763-4c6d-9a7c-41a1acd0ee47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>1ace58e6-b2b1-40c7-90f2-6ea279b97ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtQty' and @type = 'text']</value>
      <webElementGuid>c7fa79e3-dcd4-4dde-878d-6aeca3a757a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
