<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Always ask for trading pin_rbTrdgPpt</name>
   <tag></tag>
   <elementGuidId>84926744-b184-45d3-a372-535bec090e94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='rbTrdgPpt'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > div > input[name=&quot;rbTrdgPpt&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b5f8bf2-2698-4432-a7a4-37fa538588ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e6dc2d84-6d60-49b5-90a8-bc388c9d73a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rbTrdgPpt</value>
      <webElementGuid>fba4f004-f513-4da1-999e-b277dce2ca53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b01df6f0-36f0-4063-a909-eb36726d8501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divStkQteWnd&quot;)/div[@class=&quot;ui-ordtrdgpin-dlg ui-draggable ui-draggable-handle&quot;]/div[@class=&quot;ui-ordtrdgpin_opt&quot;]/fieldset[1]/div[1]/div[2]/div[1]/input[1]</value>
      <webElementGuid>af5a9d14-2749-4c3e-8366-f1afa4a70c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframeifrm</value>
      <webElementGuid>cca89468-faa4-4255-9097-5409de359228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='rbTrdgPpt'])[2]</value>
      <webElementGuid>a40bea06-59e6-492c-b103-9368871f1bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divStkQteWnd']/div[6]/div[4]/fieldset/div/div[2]/div/input</value>
      <webElementGuid>64201110-0176-477c-be4b-daf835074ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/div/input</value>
      <webElementGuid>1b678901-163c-4091-898a-59fcd8406d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rbTrdgPpt']</value>
      <webElementGuid>6c317c54-531e-4b83-a466-af1a434c3c22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
