<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_All StocksCtrlZ</name>
   <tag></tag>
   <elementGuidId>f74c3406-7663-4c62-8367-dfd4895253aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@value='1924']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ui-sq-allstk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6052c008-60f4-4576-89b5-04cfd3d0655b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1924</value>
      <webElementGuid>5de3920d-8b5a-49d8-9a43-a6c08aeca477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-sq-allstk</value>
      <webElementGuid>2677d928-ce3f-4979-b65d-9cfa9771041b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All StocksCtrl+Z</value>
      <webElementGuid>f2787324-b652-41b3-8f07-2a1155e9de3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-stkgrp&quot;)/ul[1]/li[@class=&quot;ui-sm&quot;]/ul[@class=&quot;ui-menu-2&quot;]/li[@class=&quot;ui-sq-allstk&quot;]</value>
      <webElementGuid>96c9cad3-56ed-4519-b5e7-42c80e42b831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframeifrm</value>
      <webElementGuid>d347f517-d432-47b6-a15a-dd068ddd3916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@value='1924']</value>
      <webElementGuid>c6dfe299-b083-444f-9e79-f0c1afee8579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='nav-stkgrp']/ul/li/ul/li[4]</value>
      <webElementGuid>f9d04f90-d469-4a75-a1a1-50b77140e5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift+3'])[1]/following::li[1]</value>
      <webElementGuid>22d85fc5-f4f4-4b76-be1d-0738976c6f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Stocks']/parent::*</value>
      <webElementGuid>9182233d-be4d-4b8c-817f-79a09cbed0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/nav/ul/li/ul/li[4]</value>
      <webElementGuid>b53dc26d-8493-423e-b3bb-091c9c471935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'All StocksCtrl+Z' or . = 'All StocksCtrl+Z')]</value>
      <webElementGuid>e8602512-a364-4a14-a683-4bd660693b49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
