<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Total 0 order_ui-om_buy_oths</name>
   <tag></tag>
   <elementGuidId>9daa1f75-72f9-41bd-bf45-59694f0f3eae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='csom_id']/div/div[2]/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-om_buy_oths</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e50753e1-ead4-4832-8414-1fb52d46da86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-om_buy_oths</value>
      <webElementGuid>67eee4ad-fc3a-43f0-b5f0-cff5e2b333db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;csom_id&quot;)/div[@class=&quot;ui-csom-cntnr&quot;]/div[@class=&quot;ui-csom-ord&quot;]/span[@class=&quot;ui-om_buy_oths&quot;]</value>
      <webElementGuid>d53dbb47-f6c5-46f9-bb14-96c83bcaa76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframeifrm</value>
      <webElementGuid>fd7e940c-c99a-4b3b-af52-3e13e7cd19c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='csom_id']/div/div[2]/span[3]</value>
      <webElementGuid>b33597fd-87ef-492f-b178-ec5e496b3428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[3]</value>
      <webElementGuid>b76d0007-cdae-4483-9f31-bbb47f22a10a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
