<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_9.150</name>
   <tag></tag>
   <elementGuidId>e46e072a-ecee-45b6-8426-9a45fd3de937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spPx7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#spPx7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ca3b0d49-556d-4e76-926d-c19b0f6a774c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spPx7</value>
      <webElementGuid>ed174ac3-b43c-48b4-9d14-799a557f8b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-cfs-up</value>
      <webElementGuid>ddcce155-7780-4b24-9757-521f427802c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9.150</value>
      <webElementGuid>32caf9f4-bca2-4243-bca2-ccdc23e784fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spPx7&quot;)</value>
      <webElementGuid>2a0510c1-5aad-4cda-8192-4ae45ae62095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframeifrm</value>
      <webElementGuid>70edfef3-9ba7-4373-8f41-70c6f42bd765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='spPx7']</value>
      <webElementGuid>f24179a5-5879-4ae8-a880-2f336ddbfca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divStkQteWnd']/div[5]/div[5]/div/div[5]/span[8]</value>
      <webElementGuid>eb8bc657-dab9-4f1d-b9b0-c5c88d59dc51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price >>'])[1]/following::span[7]</value>
      <webElementGuid>e9e350dd-f69f-4572-b309-ff302773ba01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3946]/following::span[20]</value>
      <webElementGuid>8d9d342c-679c-41d2-97c8-177282f2e659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price &lt;&lt;'])[1]/preceding::span[5]</value>
      <webElementGuid>f6e516e5-3ca4-4bae-a3b1-542a5b7f58fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lots'])[1]/preceding::span[17]</value>
      <webElementGuid>13b87587-c47c-4bef-82b3-ef502130cc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='9.150']/parent::*</value>
      <webElementGuid>ab8c1794-be10-4770-95d6-9525048d13af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span[8]</value>
      <webElementGuid>2c0090e3-47ba-4fd0-a80f-f7698756d06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'spPx7' and (text() = '9.150' or . = '9.150')]</value>
      <webElementGuid>37b955a5-287a-4bdd-a080-e0c41e6f604a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
