<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_5</name>
   <tag></tag>
   <elementGuidId>d59f1522-3559-4d44-a758-4f31387181a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divStkQteWnd']/div[5]/div[4]/div/div/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-ordent-qty_det > div > span:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2542d0a9-52c0-462f-a6a4-779b76f43ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0fb8baa9-25b2-4abd-b3ff-e81542b67f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divStkQteWnd&quot;)/div[@class=&quot;ui-om-ordent ui-draggable ui-draggable-handle&quot;]/div[@class=&quot;ui-ordent-qty&quot;]/div[@class=&quot;ui-ordent-qty_det&quot;]/div[1]/span[3]</value>
      <webElementGuid>e1775810-e978-4850-944e-6b20ecdd6a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframeifrm</value>
      <webElementGuid>70b2fb20-f156-46f6-ab1c-c2a13ef179e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divStkQteWnd']/div[5]/div[4]/div/div/span[3]</value>
      <webElementGuid>2361c6d2-f210-49ba-9b47-9811ba869d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Quantity:'])[1]/following::span[3]</value>
      <webElementGuid>3efbfebf-0c21-46f4-aba8-f12d0d1d1b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- HO WEI CHEONG'])[1]/following::span[4]</value>
      <webElementGuid>c01dc1c9-1d9c-4479-96ee-8ce6878b0cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Price:'])[1]/preceding::span[13]</value>
      <webElementGuid>15356198-0308-43e0-a3f2-5711751a7d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span[3]</value>
      <webElementGuid>f2a4ff17-6c6c-49f8-9412-88d82d4c73fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '5' or . = '5')]</value>
      <webElementGuid>e83727b9-2b7b-4f27-a90b-2f982f4a237f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
