<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Most Active (Volume)</name>
   <tag></tag>
   <elementGuidId>cb6944c6-c7b2-4bc7-adc4-18a9c2bd1ac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@value='1900']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav#nav-stkgrp>ul>li:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>20e051d7-5d0a-485f-a09f-fc2d8f8d4a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b820b818-bc3b-4b02-b31e-915cd456d3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-sm-disp</value>
      <webElementGuid>a0850383-8482-487b-9b3b-a50578b76b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1900</value>
      <webElementGuid>93dcb0de-9ec8-4f06-bfc9-1b39297b21d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wcd</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>d0130407-6f6f-4a9b-a89d-7c2b7bf4caea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Most Active (Volume)</value>
      <webElementGuid>f7e3a9ed-ec98-468c-bcd2-96d6f0cd096a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-stkgrp&quot;)/ul[1]/li[@class=&quot;ui-sm&quot;]/span[@class=&quot;ui-sm-disp&quot;]</value>
      <webElementGuid>e6972b23-2d59-44fc-abcd-cba875d2ef14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframeifrm</value>
      <webElementGuid>980c0f62-e5bb-4cfb-a3a4-ad1e27b17d8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@value='1900']</value>
      <webElementGuid>81c6b414-3d7d-4151-89b9-e0be8cfa312c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='nav-stkgrp']/ul/li/span</value>
      <webElementGuid>b7de0225-f722-45c6-83f2-e89fa9ad2952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records to view'])[1]/following::span[1]</value>
      <webElementGuid>524059db-69f1-459c-863f-0f65325692ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::span[4]</value>
      <webElementGuid>cc3fc2cc-4f1b-4dea-8e3d-214eda4e3a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift+1'])[1]/preceding::span[1]</value>
      <webElementGuid>e0a156af-9110-4222-8742-31e3945933e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Most Active (Volume)']/parent::*</value>
      <webElementGuid>a0d29ad2-7fd3-445a-8376-4ec3587bf764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/nav/ul/li/span</value>
      <webElementGuid>909224b7-7cb5-4ad5-9c01-730d67dbd44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Most Active (Volume)' or . = 'Most Active (Volume)')]</value>
      <webElementGuid>71643994-613e-47ab-96e1-d074469f105d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
