<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Normal Order</name>
   <tag></tag>
   <elementGuidId>bad2b436-a55e-42ca-b39d-957d9647a887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divStkQteWnd']/div[3]/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-buy-normord-r</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>26c134e9-23a2-4d68-8652-45ea34e44fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-buy-normord-r</value>
      <webElementGuid>7e99ca81-d9f1-495b-ba34-634cc69d12d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Normal Order</value>
      <webElementGuid>20e311c2-7b39-4739-9d12-96dfe6c01c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divStkQteWnd&quot;)/div[@class=&quot;ui-om_buy_mn&quot;]/li[@class=&quot;ui-buy-normord&quot;]/span[@class=&quot;ui-buy-normord-r&quot;]</value>
      <webElementGuid>1559fa87-4431-4fd7-994a-eae4df1ad809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframeifrm</value>
      <webElementGuid>92eff4d8-3ab3-44a3-a53a-239025b23f11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divStkQteWnd']/div[3]/li/span</value>
      <webElementGuid>6aae03e4-f6af-432d-b3c3-f9cd7a60a805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3931]/following::span[1]</value>
      <webElementGuid>ffbb6b84-43c5-4ba4-b76e-9d93c7b9f7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDSS'])[2]/preceding::span[1]</value>
      <webElementGuid>fca04c2f-8814-43c7-9184-88749d373fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Normal Order']/parent::*</value>
      <webElementGuid>da05a6df-e8f6-4479-9dcf-d4e82451bd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/li/span</value>
      <webElementGuid>8c4bbf9f-bf95-4346-9177-452ca68f7784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Normal Order' or . = 'Normal Order')]</value>
      <webElementGuid>5ab3cf75-8874-42f9-ad69-ac3a2d6cf65e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
