<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_0012</name>
   <tag></tag>
   <elementGuidId>d4377ad3-fab2-4120-af9a-d65b1013dba1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.ui-cfs-stk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>54d51983-761c-46e1-afc3-eb0cff80a83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>16577dda-0901-488a-a558-51e44c1f1b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>grid_id_stock_code</value>
      <webElementGuid>0af326b2-cf98-439d-852d-38b4eb2aecd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-cfs-stk</value>
      <webElementGuid>42e5563e-2d0f-4dc9-aa40-4c815dee4942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0012</value>
      <webElementGuid>9f19be5a-b5b5-40fd-9c44-348f947bcf3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;10&quot;)/td[@class=&quot;ui-cfs-stk&quot;]</value>
      <webElementGuid>ee16f5da-38de-4859-9f07-377fabeb97d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MaybankTrade/Page_Maybank IB Trading Portal/iframeifrm</value>
      <webElementGuid>c5187122-8be6-4b1a-92dd-3809cea2d050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='10']/td</value>
      <webElementGuid>47e7cec6-335e-41f0-8c1b-1a2dec83424c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vol/VMA Chg% (90)'])[1]/following::td[535]</value>
      <webElementGuid>be597adb-7847-4ec5-a035-e4f793e87936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vol/VMA Chg% (5)'])[1]/following::td[535]</value>
      <webElementGuid>dcc1b4f3-dd8c-4fc9-9469-b6ab3a488728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='°'])[1]/preceding::td[1]</value>
      <webElementGuid>a89b7ecf-65f1-4f0a-9752-09c4b820e904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::td[2]</value>
      <webElementGuid>884e20be-2272-4ab1-8f02-1b94c4584300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0012']/parent::*</value>
      <webElementGuid>ada3abaf-f0e3-4f7e-aa06-76d5f2a89773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>4a747bf0-3704-4bda-be3e-7dfb78942e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '0012' or . = '0012')]</value>
      <webElementGuid>85fd64c7-cc82-4291-8232-67bb970297c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
