<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ClickHere</name>
   <tag></tag>
   <elementGuidId>48ed5909-fac5-4fa1-b745-4b47ec628abc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='u_5_6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_5_6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b32af991-dcdd-4b2a-936f-78bc03ef2fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>321d6950-623b-4cf3-9263-e475ab7c9767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_5_6</value>
      <webElementGuid>b0609dee-d86b-47a1-8a47-fd148eb9fe45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>myFunction()</value>
      <webElementGuid>a36ff45d-ed3b-44ae-95ba-09552dc78090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click
		Here</value>
      <webElementGuid>63e46930-9292-49eb-aa53-93229ec8a514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_5_6&quot;)</value>
      <webElementGuid>ad37f24a-0850-45f6-bcae-6fa084a90497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NestedFrame/Page_Nested iFrames Example  Dezlearn  Lear_6a16ae/iframe_ClickHere_demo_frame1</value>
      <webElementGuid>718d16af-9b04-44ad-8387-9d9ef7035769</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='u_5_6']</value>
      <webElementGuid>7c1242ec-1162-4ae8-944f-3357e681cf14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iframe 2'])[1]/following::button[1]</value>
      <webElementGuid>529fd2ad-440f-4250-9d4a-221e62efd8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'u_5_6', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>6fb8f09e-a077-4639-8e9c-517425d6e134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2741e327-ad82-4de1-b472-ed1d37c3682c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'u_5_6' and (text() = 'Click
		Here' or . = 'Click
		Here')]</value>
      <webElementGuid>d6b4a383-3f04-4cb6-9344-f43379716edc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
