<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ClickHere (1)</name>
   <tag></tag>
   <elementGuidId>7a224661-a5be-4444-b4b3-cdd0a5289fe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='u_5_5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_5_5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0df9020a-1c13-4a15-a0a3-3d6232b1c1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68f7913c-7d69-41a5-9d06-6a3be24790a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_5_5</value>
      <webElementGuid>c6259fd6-1bdd-49f4-bbaa-0860c266a883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>myFunction()</value>
      <webElementGuid>bf2dac63-ea0d-4378-8986-4f4e5f67981f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click
			Here</value>
      <webElementGuid>6955c763-1108-43d6-bea0-b058f5229443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_5_5&quot;)</value>
      <webElementGuid>186f4409-76be-4604-b268-8f0e18404c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NestedFrame/Page_Nested iFrames Example  Dezlearn  Lear_6a16ae/iframe_Nested iFrames Example_demo_parent_iframe</value>
      <webElementGuid>73926378-9e30-4378-80c7-311299923354</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='u_5_5']</value>
      <webElementGuid>009ac8a9-b8ca-44ec-9507-59a3faba473e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parent iframe'])[1]/following::button[1]</value>
      <webElementGuid>08924f09-d3cd-40c7-9f51-85c4b1169298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'u_5_5', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>0a87f5ee-11ca-420a-a704-b7fe6e384341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d4929eb8-16d4-4771-9b9f-6f6b10f313a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'u_5_5' and (text() = 'Click
			Here' or . = 'Click
			Here')]</value>
      <webElementGuid>8d909315-6bdd-446a-9744-edef5fc0c249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
