<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Terms and Conditions_ml-webforms-pop_d1c6fc</name>
   <tag></tag>
   <elementGuidId>91aec646-84d6-4086-8325-d60689d5e774</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ml-webforms-popup-3672985']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ml-webforms-popup-3672985</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5b7baa1c-bb1c-4c8e-9523-9d0ffc7310db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ml-webforms-popup-3672985</value>
      <webElementGuid>521d8d45-bda3-4f27-a94a-51d22fa4df2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>show-overlay</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b3208aa5-eb47-4914-ab60-f8cf3b29498c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MailerLite Form</value>
      <webElementGuid>9bd233d8-05b7-4c7b-87e3-52b07759668d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.mailerlite.com/proxy/abdata/?url=/1383/1383146/webforms/g8j9s3/3672/3672985/page.html&amp;v=1695396742</value>
      <webElementGuid>5be8f66c-770c-478c-a562-22bb4fb1f150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e217dbe5-0c3b-439c-8c68-8c362827c000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>animation</name>
      <type>Main</type>
      <value>fadeIn</value>
      <webElementGuid>dc255069-d716-453a-a328-c93356000d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ml-webforms-popup-3672985&quot;)</value>
      <webElementGuid>88b20725-acdc-48e3-a369-c7c50bd8535c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ml-webforms-popup-3672985']</value>
      <webElementGuid>61e129a9-0e3b-46de-a3a3-1ca3bfe0c197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/iframe</value>
      <webElementGuid>7bb42544-96de-4eaa-8c85-6636ac2df140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ml-webforms-popup-3672985' and @title = 'MailerLite Form' and @src = 'https://app.mailerlite.com/proxy/abdata/?url=/1383/1383146/webforms/g8j9s3/3672/3672985/page.html&amp;v=1695396742']</value>
      <webElementGuid>3ccf1b17-0f1d-48c1-bf14-f9dd1b3a96eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
