<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nested iFrames Example_demo_parent_iframe</name>
   <tag></tag>
   <elementGuidId>c9fcfba9-92a7-4fb0-97cd-d407b76cb391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='parent_iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#parent_iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>150ed674-ce3d-4bf9-8787-2266e112c146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>parent_iframe</value>
      <webElementGuid>f43cf011-bd66-499f-85d3-584055486e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demo_parent_iframe</value>
      <webElementGuid>4fd31bfb-db35-426f-ad7d-47d45e869e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>700</value>
      <webElementGuid>e711cf7b-5f40-49a9-8354-e02c25f38b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>514581bd-c533-4d6c-88e0-c98c6a39bd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bit.ly/38erOdQ</value>
      <webElementGuid>07f2e0f8-042e-4253-870e-360ea7bd8c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parent_iframe&quot;)</value>
      <webElementGuid>e20b8da7-0c61-4f8e-b1f4-48c9b8aba2c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='parent_iframe']</value>
      <webElementGuid>e816c0d0-eddf-461d-a5f8-789f5eef8344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-9381']/div/div/section/div/div/div/section/div/div/div/div/div/div/iframe</value>
      <webElementGuid>d0e61301-da95-438c-935c-8991c62c4e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nested iFrames Example'])[2]/following::iframe[1]</value>
      <webElementGuid>2160e50f-031d-4e61-97ec-bd267696c6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join'])[1]/following::iframe[1]</value>
      <webElementGuid>965c0d8a-8966-4c28-ab08-fcecc5fd9aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Courses'])[2]/preceding::iframe[1]</value>
      <webElementGuid>a85dae58-8b4e-4a06-84df-ed4563a1bbcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium WebDriver with Java'])[1]/preceding::iframe[1]</value>
      <webElementGuid>777fa57f-b3be-4c14-84c5-1c49ba30ab66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a291892b-c2ed-4ee0-be43-bf5beeac2749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'parent_iframe' and @name = 'demo_parent_iframe' and @src = 'https://bit.ly/38erOdQ']</value>
      <webElementGuid>b8a40173-5b44-4faf-9c2f-170e3dc3a57f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
