<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_ClickHere_demo_frame1</name>
   <tag></tag>
   <elementGuidId>d59ee300-c4c2-44af-874c-fc011c7bc30c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframe1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ce7515ea-0597-4581-8139-af57c69804cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe1</value>
      <webElementGuid>d7ba0f90-ef4a-4157-b6a2-20a6493719df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demo_frame1</value>
      <webElementGuid>d58e0d01-a863-42fd-b3ea-cc3790e9f144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>57f59319-a81a-489a-8ea8-883fc49b3dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>e13441d9-c3b5-4f40-bbb6-0638a6e77d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bit.ly/3re1ic9</value>
      <webElementGuid>7dc7fb0f-ddee-49ea-b75e-8eee64b8be88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe1&quot;)</value>
      <webElementGuid>313f9ac7-45d3-48f8-ae37-43886ef5b21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NestedFrame/Page_Nested iFrames Example  Dezlearn  Lear_6a16ae/iframe_Nested iFrames Example_demo_parent_iframe</value>
      <webElementGuid>b47ae899-e036-45fc-8e44-093a5887ca3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe1']</value>
      <webElementGuid>dd0112cf-5210-4e80-be5c-cc21b794acae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7cf6207d-edd7-42d7-aa71-e5ebf2c286dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframe1' and @name = 'demo_frame1' and @src = 'https://bit.ly/3re1ic9']</value>
      <webElementGuid>74992ee0-33ac-49fc-875f-0829582c46a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
