<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit as New</name>
   <tag></tag>
   <elementGuidId>a651651f-0228-4c67-9441-baf6a6c91a74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-1hg3so9-2.dHPFUr.StyledButton-sc-qe3ace-0.eMaKcV</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[47]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8412f86-251a-4c36-8786-2a5dd2fd6cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-garden-id</name>
      <type>Main</type>
      <value>buttons.button</value>
      <webElementGuid>53781394-c225-421c-9098-5679ada2c24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-garden-version</name>
      <type>Main</type>
      <value>8.73.2</value>
      <webElementGuid>a6825bff-7cde-4b27-b7e4-256305187e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3a46fc77-aa18-4565-aa30-970740327cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>submit_button-button</value>
      <webElementGuid>0f4296d9-a16b-44f8-ab5c-c43609d11be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-id</name>
      <type>Main</type>
      <value>submit_button-button</value>
      <webElementGuid>4623b53f-58a0-4d6c-87c6-8deb47939802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-support-suite-trial-onboarding-id</name>
      <type>Main</type>
      <value>submitReply</value>
      <webElementGuid>18fa41fa-9c32-4963-a4df-fbb112e0c016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1hg3so9-2 dHPFUr StyledButton-sc-qe3ace-0 eMaKcV</value>
      <webElementGuid>bb6a4ed8-49b7-46bb-ab5a-7ab25b246d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit as New</value>
      <webElementGuid>0f484669-b8c2-4559-8455-f068d8bcc988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember3358&quot;)/footer[@class=&quot;sc-1aclnqv-0 jZsJOj StyledFooter-sc-v7lib2-0 hbFKRW&quot;]/div[@class=&quot;sc-177ytgv-0 eCbnKr&quot;]/div[@class=&quot;sc-177ytgv-1 gelOcs&quot;]/div[@class=&quot;StyledFooterItem-sc-1cktm85-0 heIGWh&quot;]/div[@class=&quot;sc-1hg3so9-1 jaFKFc StyledButtonGroup-sc-1fbpzef-0 hRCOTE&quot;]/button[@class=&quot;sc-1hg3so9-2 dHPFUr StyledButton-sc-qe3ace-0 eMaKcV&quot;]</value>
      <webElementGuid>46f0175a-5b83-48b5-9700-d76395ac8bee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[47]</value>
      <webElementGuid>951ed0e5-08e4-4afe-94a8-31b2334d9f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember3358']/footer/div/div[3]/div[2]/div/button</value>
      <webElementGuid>533f6a98-a270-40e0-8c84-6e02b03fe582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/button</value>
      <webElementGuid>0ebb8aed-1aa5-4b92-b1f2-b7ee3c1d81b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Submit as New' or . = 'Submit as New')]</value>
      <webElementGuid>80c0ebde-e4ca-4fee-bf5e-cc6c4c267a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
