<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Click to DownloadGenerating Download Link_632ef4</name>
   <tag></tag>
   <elementGuidId>8ff169f1-2922-4296-b014-3e0add7c7418</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#download-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='download-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64c32081-152b-455b-8777-8b4721647678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>download-btn</value>
      <webElementGuid>c595d002-77dc-47aa-a99b-146c8a113e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://s1-filecr.xyz/58ccaef264709e06?ref=b789015a85f2b58893957c80f6d6cc53</value>
      <webElementGuid>30ff8fdc-951f-4bf7-8806-f8aaef62f627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sh_download-btn  done</value>
      <webElementGuid>e2735bf3-6d4b-4eed-9486-d143db2e6439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>22ca141e-e53c-496c-8847-23d54096969b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>8977fee0-3d5a-448f-ad2d-c2fbf73e8380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click to DownloadGenerating Download LinkSuccessful</value>
      <webElementGuid>291fef82-0d29-4a35-8606-4513ec514e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;download-btn&quot;)</value>
      <webElementGuid>0677bf20-7929-4ad5-a3b2-358b56ae7a7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='download-btn']</value>
      <webElementGuid>3c728d00-78f8-451c-870b-4f626a12d630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/div[2]/div/a</value>
      <webElementGuid>f491d0ff-3479-4e5f-ac3e-d8c8b7063b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MediaHuman YouTube Downloader'])[1]/following::a[1]</value>
      <webElementGuid>d700ce23-9944-4e80-9b90-e56fc2aff1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanks for Downloading'])[1]/following::a[2]</value>
      <webElementGuid>afaa3353-b399-4b32-971f-5caed944bb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://s1-filecr.xyz/58ccaef264709e06?ref=b789015a85f2b58893957c80f6d6cc53')]</value>
      <webElementGuid>b0a49c2f-bf97-4d3a-970e-a85f7f90d75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>a7e813f6-b499-4664-9103-5b787705d6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'download-btn']</value>
      <webElementGuid>2f03175e-c9c2-4039-9faa-8af4e29e6f62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
