<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WindowManager 10.13.4</name>
   <tag></tag>
   <elementGuidId>032fadf9-0adb-4536-ab2f-31ca6a12f22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.card_title__az7G7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/main/section/section/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2757d86f-2e76-4fb8-ada2-536bb0728a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_title__az7G7</value>
      <webElementGuid>a5c04080-c52a-42ea-9bfd-41b5aea3220a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/windows/windowmanager/</value>
      <webElementGuid>534b8221-b01e-4fba-aa7f-2b8cb3fa42de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WindowManager 10.13.4</value>
      <webElementGuid>68a57c95-bf5c-4e3c-a82f-e09b15c655fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;content&quot;]/main[@class=&quot;main&quot;]/section[@class=&quot;products&quot;]/section[@class=&quot;products&quot;]/div[@class=&quot;product-list&quot;]/div[1]/div[@class=&quot;card_wrap__S35wt&quot;]/div[@class=&quot;card_info__LY5ob&quot;]/a[@class=&quot;card_title__az7G7&quot;]</value>
      <webElementGuid>c45bad13-0ede-43ff-8775-87ce4e881c4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/main/section/section/div/div/div/div/a</value>
      <webElementGuid>d8ca751e-9ea9-4695-a72c-aa46481014f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WindowManager 10.13.4')]</value>
      <webElementGuid>58fbedcc-9d64-488c-8062-e0921b3e58a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download (Low to high)'])[1]/following::a[2]</value>
      <webElementGuid>89876eec-3121-4793-a55a-4cadb6081944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download (High to low)'])[1]/following::a[2]</value>
      <webElementGuid>8f3cf3ff-fa8d-4b56-bf90-024af355c9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desktop Enhancement'])[1]/preceding::a[1]</value>
      <webElementGuid>33abea6b-fecd-4f8a-8a3a-8d72eaf548a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='windows'])[1]/preceding::a[2]</value>
      <webElementGuid>4282e9cd-e132-45dd-b951-771c612bbb89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WindowManager 10.13.4']/parent::*</value>
      <webElementGuid>7835c496-fd2d-4e6b-861a-4388999e810e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/windows/windowmanager/')])[2]</value>
      <webElementGuid>b32207cd-4a4c-4842-b8a7-aa4b08d6cf69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/a</value>
      <webElementGuid>5a66be61-f624-4b9c-a588-8ed99a7f2396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
