<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CommandBar_DeleteButton</name>
   <tag></tag>
   <elementGuidId>your_guid_here</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[id*='DeleteButton']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@id,'DeleteButton')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
