<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>efd71d09-1c9b-4f2b-9409-663c4cf0b916</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.leftsection > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='control']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f40550b7-8d49-47ee-ab20-4e68e351c8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../cms/files/HeroBanner1_Carousel1_Desktop-mi.jpg?quality=80</value>
      <webElementGuid>4726076f-5a65-4ccd-a229-2efaad11a028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;control&quot;)/div[@class=&quot;homebannercontainer item ctracking&quot;]/div[@class=&quot;leftsection&quot;]/img[1]</value>
      <webElementGuid>a82f82f7-8e48-47d2-8560-c105f2e66e2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='control']/div/div/img</value>
      <webElementGuid>37673233-0118-4d2b-8e27-9c203ff4f562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/img</value>
      <webElementGuid>121c70ce-dde1-430e-9163-a812468e2d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../cms/files/HeroBanner1_Carousel1_Desktop-mi.jpg?quality=80']</value>
      <webElementGuid>ef1c6788-95ef-4c42-9f0c-a77965366eee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
