<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add note</name>
   <tag></tag>
   <elementGuidId>007a0bac-e001-4dd6-badc-3775dd73551e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id-0b119b8f-c289-4a5e-b354-03d458c38426-8-notescontrol-undefinedsave_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id-0b119b8f-c289-4a5e-b354-03d458c38426-8-notescontrol-undefinedsave_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71c4bd3f-0e34-43ff-8059-59b52b62c714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-0b119b8f-c289-4a5e-b354-03d458c38426-8-notescontrol-undefinedsave_button</value>
      <webElementGuid>83031863-f522-4d8f-b717-8c2fe55ad41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add note</value>
      <webElementGuid>64b78130-7151-4805-809c-064343acb8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>notescontrol-undefinedsave_button</value>
      <webElementGuid>684b1143-fcac-4a8f-8ac4-ceeb8e23c1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa1284b9-f1cb-4dec-84db-c0dd0ba79610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-ty pa-of pa-ao pa-be pa-hm pa-jr pa-in pa-tz pa-ua pa-e pa-gq pa-gr pa-lt pa-ub pa-uc pa-ud pa-kc pa-ue pa-uf pa-ug pa-uh pa-ui text-button </value>
      <webElementGuid>8e7ed339-9c68-4492-a2ef-8edbb8a308da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-landmark-active-element</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a6b30f2f-b1bd-4888-9d27-708ab3407161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add note</value>
      <webElementGuid>d6a9bf7b-aecc-4bfe-82f8-e9d4cde6e1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-0b119b8f-c289-4a5e-b354-03d458c38426-8-notescontrol-undefinedsave_button&quot;)</value>
      <webElementGuid>deda47b1-854c-4897-b394-6f719def969f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-0b119b8f-c289-4a5e-b354-03d458c38426-8-notescontrol-undefinedsave_button']</value>
      <webElementGuid>f9eb0cbb-75fb-450b-8535-6150607c3802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-0b119b8f-c289-4a5e-b354-03d458c38426-8-notescontrol-timeline_wall_container']/div/div[3]/div/div[2]/div[2]/button</value>
      <webElementGuid>f09bb494-f177-4edd-8707-1516e7d9354b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a note'])[1]/following::button[3]</value>
      <webElementGuid>9fcd4c76-2b1e-4fd4-bbdb-46f2b8adfa41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timeline'])[1]/following::button[8]</value>
      <webElementGuid>4922d514-f593-4bf9-aa4b-7b7400f03ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>d6dec45c-13de-44e9-858d-292c530ca4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get started'])[1]/preceding::button[2]</value>
      <webElementGuid>b2cab2a8-40b1-4b39-909c-0d70f4bac9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add note']/parent::*</value>
      <webElementGuid>a4cd8544-43c9-480c-ae5b-8d977738f081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>faf15291-e2a9-4316-a08d-f21773d6a72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add note' or . = 'Add note')]</value>
      <webElementGuid>4e92e932-fd0d-4a3a-b9cb-9257fc84847f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
