<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>78499ea8-b453-46ab-b1b9-e531720a595d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='FullPage_a7894da3d91011695644595825']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f4ead2f-759d-4cf5-917a-a9ddc5e628a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FullPage_a7894da3d91011695644595825&quot;)/div[1]/div[1]</value>
      <webElementGuid>0228b860-82cf-448a-8d19-7a5b89448721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Powerapps/Page_Team Project Information Cloud Computing -/iframe_Press ALT 0 for help_cke_wysiwyg_frame cke_reset</value>
      <webElementGuid>5b62db01-02e9-4007-81f5-b87e4faf26dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='FullPage_a7894da3d91011695644595825']/div/div</value>
      <webElementGuid>7ab4e84a-da31-4a2b-80a5-553cbde554ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]'])[1]/preceding::div[1]</value>
      <webElementGuid>093db198-2c90-4c2f-b6c3-2a7b6d8ffc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]'])[2]/preceding::div[3]</value>
      <webElementGuid>6f1afd47-b569-46b5-a5c7-3822e8be8807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>24ce280a-d0c1-48ae-8e1a-253296a3d4f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
