<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hello</name>
   <tag></tag>
   <elementGuidId>393bd61e-fccb-49b0-a968-a7c8c8e1cbf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='FullPage_a7894da3d91011695644595825']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>afde2864-0804-4fe2-985a-b4d006c679a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello</value>
      <webElementGuid>2b30f05f-3617-42a3-8c86-452ded47fb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FullPage_a7894da3d91011695644595825&quot;)/div[1]/div[1]</value>
      <webElementGuid>bc1e09ac-52e7-4454-9d22-fa7a13b49038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Powerapps/Page_Team Project Information Cloud Computing -/iframe_Press ALT 0 for help_cke_wysiwyg_frame cke_reset</value>
      <webElementGuid>8772751f-7901-4c5c-a214-90a5f5fd825a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='FullPage_a7894da3d91011695644595825']/div/div</value>
      <webElementGuid>c34bec5a-22b2-4cd7-ab5b-13bd62110691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How are you'])[1]/preceding::div[1]</value>
      <webElementGuid>b81985ca-f06f-4bea-8b11-b774f51ed16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]'])[1]/preceding::div[2]</value>
      <webElementGuid>1909a4a4-a6a3-49b2-8c41-78ff4f99d523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hello']/parent::*</value>
      <webElementGuid>1f6666a1-136e-4695-a7b6-1cf0d344a726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>d0f77fa8-082c-4282-88dc-972657bc082e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hello' or . = 'Hello')]</value>
      <webElementGuid>ac1c1acb-ac39-45dd-8dec-4709886fe533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
