<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>html_Description rich text editorkatalonfon_29454e</name>
   <tag></tag>
   <elementGuidId>aba61cf6-796e-4bdf-931a-0708bcb91d56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>html</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>html</value>
      <webElementGuid>b8b6b169-e332-4742-82b5-dcedd14dae36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>71d632e6-8190-4a10-b6e5-2bd360a6ce20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description rich text editor#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}html{cursor:text;*cursor:auto}
img,input,textarea{cursor:default}#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}@media(forced-colors: active){.cke_editable {forced-color-adjust: preserve-parent-color;}}NaN
.cke_contents_ltr a.cke_anchor,.cke_contents_ltr a.cke_anchor_empty,.cke_editable.cke_contents_ltr a[name],.cke_editable.cke_contents_ltr a[data-cke-saved-name]{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat left center;border:1px dotted #00f;background-size:16px;padding-left:18px;cursor:auto;}.cke_contents_ltr img.cke_anchor{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat left center;border:1px dotted #00f;background-size:16px;width:16px;min-height:15px;height:1.15em;vertical-align:text-bottom;}.cke_contents_rtl a.cke_anchor,.cke_contents_rtl a.cke_anchor_empty,.cke_editable.cke_contents_rtl a[name],.cke_editable.cke_contents_rtl a[data-cke-saved-name]{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat right center;border:1px dotted #00f;background-size:16px;padding-right:18px;cursor:auto;}.cke_contents_rtl img.cke_anchor{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat right center;border:1px dotted #00f;background-size:16px;width:16px;min-height:15px;height:1.15em;vertical-align:text-bottom;}
.openlink a:hover{ cursor: pointer; }
.cke_widget_wrapper{position:relative;outline:none}.cke_widget_inline{display:inline-block}.cke_widget_wrapper:hover>.cke_widget_element{outline:2px solid #ffd25c;cursor:default}.cke_widget_wrapper:hover .cke_widget_editable{outline:2px solid #ffd25c}.cke_widget_wrapper.cke_widget_focused>.cke_widget_element,.cke_widget_wrapper .cke_widget_editable.cke_widget_editable_focused{outline:2px solid #47a4f5}.cke_widget_editable{cursor:text}.cke_widget_drag_handler_container{position:absolute;width:15px;height:0;display:block;opacity:0.75;transition:height 0s 0.2s;line-height:0}.cke_widget_wrapper:hover>.cke_widget_drag_handler_container{height:15px;transition:none}.cke_widget_drag_handler_container:hover{opacity:1}.cke_editable[contenteditable=&quot;false&quot;] .cke_widget_drag_handler_container{display:none;}img.cke_widget_drag_handler{cursor:move;width:15px;height:15px;display:inline-block}.cke_widget_mask{position:absolute;top:0;left:0;width:100%;height:100%;display:block}.cke_widget_partial_mask{position:absolute;display:block}.cke_editable.cke_widget_dragging, .cke_editable.cke_widget_dragging *{cursor:move !important}
.cke_upload_uploading img{opacity: 0.3}
[data-msdyn-rteplaceholder]::before {position: absolute;opacity: .8;color: #323130;content: attr( data-msdyn-rteplaceholder );}.cke_wysiwyg_div[data-msdyn-rteplaceholder]::before {margin-top: 1em;}@media screen and (-ms-high-contrast: white-on-black) {[data-msdyn-rteplaceholder]::before {position: absolute;opacity: .8;color: #ffffff;content: attr( data-msdyn-rteplaceholder );}}
img::selection {color:rgba(0,0,0,0)}img.cke-img-container {outline:1px solid #c6c6c6;-moz-user-select:none;}.cke-img-resizer {position:absolute;z-index:10001}.cke-img-resizer span{display:none;position:absolute;background-size:100% 100%;outline:1px solid #c6c6c6}.cke-img-resizer i {position:absolute;display:block;width:10px;height:10px;border-radius:50%;background:#fff;border:1px solid #c6c6c6}.cke-img-resizer i.br,.cke-img-resizer i.tl {cursor:nwse-resize}.cke-img-resizer i.bm,.cke-img-resizer i.tm {cursor:ns-resize}.cke-img-resizer i.bl,.cke-img-resizer i.tr {cursor:nesw-resize}.cke-img-resizer i.lm,.cke-img-resizer i.rm {cursor:ew-resize}.cke-img-resizer-btn {background-color:white;border:none;cursor:pointer;height:15px;width:16px;position:relative}
.cke_table-faked-selection-editor *::selection,table[data-cke-table-faked-selection-table] *::selection{background:transparent}.cke_table-faked-selection{background:darkgray!important;color:black}.cke_table-faked-selection a{color:black}.cke_editable:focus .cke_table-faked-selection{background:#0076cb!important;color:white}.cke_editable:focus .cke_table-faked-selection a{color:white}.cke_table-faked-selection::-moz-selection,.cke_table-faked-selection ::-moz-selection{background:transparent}.cke_table-faked-selection::selection,.cke_table-faked-selection ::selection{background:transparent}table[data-cke-table-faked-selection-table]{cursor:cell}HelloHow are you/html[1]/html[1]/html[1]</value>
      <webElementGuid>3eadb4c3-6f90-4422-9258-dc3d56a6c975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]</value>
      <webElementGuid>1df27a7d-a3ac-4e27-853b-db3dfcd99bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Powerapps/Page_Team Project Information Cloud Computing -/iframe_Press ALT 0 for help_cke_wysiwyg_frame cke_reset</value>
      <webElementGuid>eaf7e2fb-577a-43e0-a6e4-dc8df5365e03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//html</value>
      <webElementGuid>027b7b30-35d5-4fff-bebf-1f0ddd5d9938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//html[(text() = 'Description rich text editor#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}html{cursor:text;*cursor:auto}
img,input,textarea{cursor:default}#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}@media(forced-colors: active){.cke_editable {forced-color-adjust: preserve-parent-color;}}NaN
.cke_contents_ltr a.cke_anchor,.cke_contents_ltr a.cke_anchor_empty,.cke_editable.cke_contents_ltr a[name],.cke_editable.cke_contents_ltr a[data-cke-saved-name]{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat left center;border:1px dotted #00f;background-size:16px;padding-left:18px;cursor:auto;}.cke_contents_ltr img.cke_anchor{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat left center;border:1px dotted #00f;background-size:16px;width:16px;min-height:15px;height:1.15em;vertical-align:text-bottom;}.cke_contents_rtl a.cke_anchor,.cke_contents_rtl a.cke_anchor_empty,.cke_editable.cke_contents_rtl a[name],.cke_editable.cke_contents_rtl a[data-cke-saved-name]{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat right center;border:1px dotted #00f;background-size:16px;padding-right:18px;cursor:auto;}.cke_contents_rtl img.cke_anchor{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat right center;border:1px dotted #00f;background-size:16px;width:16px;min-height:15px;height:1.15em;vertical-align:text-bottom;}
.openlink a:hover{ cursor: pointer; }
.cke_widget_wrapper{position:relative;outline:none}.cke_widget_inline{display:inline-block}.cke_widget_wrapper:hover>.cke_widget_element{outline:2px solid #ffd25c;cursor:default}.cke_widget_wrapper:hover .cke_widget_editable{outline:2px solid #ffd25c}.cke_widget_wrapper.cke_widget_focused>.cke_widget_element,.cke_widget_wrapper .cke_widget_editable.cke_widget_editable_focused{outline:2px solid #47a4f5}.cke_widget_editable{cursor:text}.cke_widget_drag_handler_container{position:absolute;width:15px;height:0;display:block;opacity:0.75;transition:height 0s 0.2s;line-height:0}.cke_widget_wrapper:hover>.cke_widget_drag_handler_container{height:15px;transition:none}.cke_widget_drag_handler_container:hover{opacity:1}.cke_editable[contenteditable=&quot;false&quot;] .cke_widget_drag_handler_container{display:none;}img.cke_widget_drag_handler{cursor:move;width:15px;height:15px;display:inline-block}.cke_widget_mask{position:absolute;top:0;left:0;width:100%;height:100%;display:block}.cke_widget_partial_mask{position:absolute;display:block}.cke_editable.cke_widget_dragging, .cke_editable.cke_widget_dragging *{cursor:move !important}
.cke_upload_uploading img{opacity: 0.3}
[data-msdyn-rteplaceholder]::before {position: absolute;opacity: .8;color: #323130;content: attr( data-msdyn-rteplaceholder );}.cke_wysiwyg_div[data-msdyn-rteplaceholder]::before {margin-top: 1em;}@media screen and (-ms-high-contrast: white-on-black) {[data-msdyn-rteplaceholder]::before {position: absolute;opacity: .8;color: #ffffff;content: attr( data-msdyn-rteplaceholder );}}
img::selection {color:rgba(0,0,0,0)}img.cke-img-container {outline:1px solid #c6c6c6;-moz-user-select:none;}.cke-img-resizer {position:absolute;z-index:10001}.cke-img-resizer span{display:none;position:absolute;background-size:100% 100%;outline:1px solid #c6c6c6}.cke-img-resizer i {position:absolute;display:block;width:10px;height:10px;border-radius:50%;background:#fff;border:1px solid #c6c6c6}.cke-img-resizer i.br,.cke-img-resizer i.tl {cursor:nwse-resize}.cke-img-resizer i.bm,.cke-img-resizer i.tm {cursor:ns-resize}.cke-img-resizer i.bl,.cke-img-resizer i.tr {cursor:nesw-resize}.cke-img-resizer i.lm,.cke-img-resizer i.rm {cursor:ew-resize}.cke-img-resizer-btn {background-color:white;border:none;cursor:pointer;height:15px;width:16px;position:relative}
.cke_table-faked-selection-editor *::selection,table[data-cke-table-faked-selection-table] *::selection{background:transparent}.cke_table-faked-selection{background:darkgray!important;color:black}.cke_table-faked-selection a{color:black}.cke_editable:focus .cke_table-faked-selection{background:#0076cb!important;color:white}.cke_editable:focus .cke_table-faked-selection a{color:white}.cke_table-faked-selection::-moz-selection,.cke_table-faked-selection ::-moz-selection{background:transparent}.cke_table-faked-selection::selection,.cke_table-faked-selection ::selection{background:transparent}table[data-cke-table-faked-selection-table]{cursor:cell}HelloHow are you/html[1]/html[1]/html[1]' or . = 'Description rich text editor#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}html{cursor:text;*cursor:auto}
img,input,textarea{cursor:default}#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}@media(forced-colors: active){.cke_editable {forced-color-adjust: preserve-parent-color;}}NaN
.cke_contents_ltr a.cke_anchor,.cke_contents_ltr a.cke_anchor_empty,.cke_editable.cke_contents_ltr a[name],.cke_editable.cke_contents_ltr a[data-cke-saved-name]{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat left center;border:1px dotted #00f;background-size:16px;padding-left:18px;cursor:auto;}.cke_contents_ltr img.cke_anchor{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat left center;border:1px dotted #00f;background-size:16px;width:16px;min-height:15px;height:1.15em;vertical-align:text-bottom;}.cke_contents_rtl a.cke_anchor,.cke_contents_rtl a.cke_anchor_empty,.cke_editable.cke_contents_rtl a[name],.cke_editable.cke_contents_rtl a[data-cke-saved-name]{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat right center;border:1px dotted #00f;background-size:16px;padding-right:18px;cursor:auto;}.cke_contents_rtl img.cke_anchor{background:url(https://orgdc85b499.crm8.dynamics.com/%7b638310436610000170%7d/webresources/msdyn_/RichTextEditorControl/libs/ckeditor_latest/plugins/link/images/anchor.png) no-repeat right center;border:1px dotted #00f;background-size:16px;width:16px;min-height:15px;height:1.15em;vertical-align:text-bottom;}
.openlink a:hover{ cursor: pointer; }
.cke_widget_wrapper{position:relative;outline:none}.cke_widget_inline{display:inline-block}.cke_widget_wrapper:hover>.cke_widget_element{outline:2px solid #ffd25c;cursor:default}.cke_widget_wrapper:hover .cke_widget_editable{outline:2px solid #ffd25c}.cke_widget_wrapper.cke_widget_focused>.cke_widget_element,.cke_widget_wrapper .cke_widget_editable.cke_widget_editable_focused{outline:2px solid #47a4f5}.cke_widget_editable{cursor:text}.cke_widget_drag_handler_container{position:absolute;width:15px;height:0;display:block;opacity:0.75;transition:height 0s 0.2s;line-height:0}.cke_widget_wrapper:hover>.cke_widget_drag_handler_container{height:15px;transition:none}.cke_widget_drag_handler_container:hover{opacity:1}.cke_editable[contenteditable=&quot;false&quot;] .cke_widget_drag_handler_container{display:none;}img.cke_widget_drag_handler{cursor:move;width:15px;height:15px;display:inline-block}.cke_widget_mask{position:absolute;top:0;left:0;width:100%;height:100%;display:block}.cke_widget_partial_mask{position:absolute;display:block}.cke_editable.cke_widget_dragging, .cke_editable.cke_widget_dragging *{cursor:move !important}
.cke_upload_uploading img{opacity: 0.3}
[data-msdyn-rteplaceholder]::before {position: absolute;opacity: .8;color: #323130;content: attr( data-msdyn-rteplaceholder );}.cke_wysiwyg_div[data-msdyn-rteplaceholder]::before {margin-top: 1em;}@media screen and (-ms-high-contrast: white-on-black) {[data-msdyn-rteplaceholder]::before {position: absolute;opacity: .8;color: #ffffff;content: attr( data-msdyn-rteplaceholder );}}
img::selection {color:rgba(0,0,0,0)}img.cke-img-container {outline:1px solid #c6c6c6;-moz-user-select:none;}.cke-img-resizer {position:absolute;z-index:10001}.cke-img-resizer span{display:none;position:absolute;background-size:100% 100%;outline:1px solid #c6c6c6}.cke-img-resizer i {position:absolute;display:block;width:10px;height:10px;border-radius:50%;background:#fff;border:1px solid #c6c6c6}.cke-img-resizer i.br,.cke-img-resizer i.tl {cursor:nwse-resize}.cke-img-resizer i.bm,.cke-img-resizer i.tm {cursor:ns-resize}.cke-img-resizer i.bl,.cke-img-resizer i.tr {cursor:nesw-resize}.cke-img-resizer i.lm,.cke-img-resizer i.rm {cursor:ew-resize}.cke-img-resizer-btn {background-color:white;border:none;cursor:pointer;height:15px;width:16px;position:relative}
.cke_table-faked-selection-editor *::selection,table[data-cke-table-faked-selection-table] *::selection{background:transparent}.cke_table-faked-selection{background:darkgray!important;color:black}.cke_table-faked-selection a{color:black}.cke_editable:focus .cke_table-faked-selection{background:#0076cb!important;color:white}.cke_editable:focus .cke_table-faked-selection a{color:white}.cke_table-faked-selection::-moz-selection,.cke_table-faked-selection ::-moz-selection{background:transparent}.cke_table-faked-selection::selection,.cke_table-faked-selection ::selection{background:transparent}table[data-cke-table-faked-selection-table]{cursor:cell}HelloHow are you/html[1]/html[1]/html[1]')]</value>
      <webElementGuid>2855cf51-d4ce-4d2b-bfed-c28f2f98bb11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
