<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Description_fullPageContentEditorFrame</name>
   <tag></tag>
   <elementGuidId>c5b139e3-1f03-4d7b-ab53-518f2f57853c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='fullPageEditorIdf80888aca679f1695644576405']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.fullPageContentEditorFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>41f34d7b-4e2d-4834-a7f9-bff6691e8ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Designer</value>
      <webElementGuid>798f1413-d320-4dab-8340-857acb3a5790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Designer</value>
      <webElementGuid>d0f7b72d-59a0-4f35-8932-f498c8f9d4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fullPageContentEditorFrame</value>
      <webElementGuid>d22f83ae-7d4a-43e9-8a06-6cfe1eccc1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullPageEditorIdf80888aca679f1695644576405&quot;)/iframe[@class=&quot;fullPageContentEditorFrame&quot;]</value>
      <webElementGuid>48eed8b6-cf7d-410c-b703-e119e9f7ef8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='fullPageEditorIdf80888aca679f1695644576405']/iframe</value>
      <webElementGuid>605907d0-1b55-4103-875b-1771c1e4b58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>360a6a2f-d60a-4fbe-8c3e-0525d2861aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Designer']</value>
      <webElementGuid>e025b23f-9e7a-45ff-9c76-5d0ebcb2f06b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
