<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create a note_create_note_medium_titl_16d920</name>
   <tag></tag>
   <elementGuidId>eae8f15f-4baa-4f54-85e2-fef1176b11d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='create_note_medium_titlenotescontrol']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#create_note_medium_titlenotescontrol</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ca8e750-cd8a-424c-97af-eafba101944f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create_note_medium_titlenotescontrol</value>
      <webElementGuid>a2ee4872-1da6-49c2-ae66-6037671761b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Create a Note title</value>
      <webElementGuid>98a2bbed-4c34-4f64-9aae-34ccb9315d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>648b141c-05b7-452e-a759-19c82b474814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>36243527-4d2a-4e2d-9c99-d06c08e29382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cd4a9026-3bd1-4818-ba3a-f38f778960ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f839d65d-519c-45f0-8438-64c69e81cbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-gk pa-kx pa-ex pa-tu pa-jr pa-kn pa-bc pa-ki pa-kj pa-kq </value>
      <webElementGuid>5fc5db42-4fff-4155-8903-538b865f141f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>H</value>
      <webElementGuid>fd203662-2197-4791-94bf-a0e4d5f9f8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-landmark-active-element</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c0bf9bb-d684-46d1-96dc-b362438ed34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_note_medium_titlenotescontrol&quot;)</value>
      <webElementGuid>e7776280-5043-4b5a-aaca-6527943c821f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='create_note_medium_titlenotescontrol']</value>
      <webElementGuid>b8cb32e3-b42c-4fe7-a709-9c3c115ebedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-0b119b8f-c289-4a5e-b354-03d458c38426-8-notescontrol-timeline_wall_container']/div/div[3]/div/div/div/input</value>
      <webElementGuid>7b9e3521-a19a-413b-a6fb-8e165ee2763d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>0bc1765f-3b55-44e3-86a7-b905c5587358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Title' and @type = 'text']</value>
      <webElementGuid>f040df6d-c67f-4e55-8f7e-4dd1259d68a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
