<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thanks for your feedback</name>
   <tag></tag>
   <elementGuidId>bb8b7038-60a2-45f4-810e-5b2c7ec9ca01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rn_AnswerFeedback_3_ThanksLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rn_AnswerFeedback_3_ThanksLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2406b2ad-b863-4806-b96d-8447359253ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rn_AnswerFeedback_3_ThanksLabel</value>
      <webElementGuid>15b396b6-3438-41c3-89b3-e76590601434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rn_ThanksLabel</value>
      <webElementGuid>7922b8e6-3dbf-452c-8a89-8e1820b55a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>54cc6e90-f06a-494c-b4e0-51cebd13d420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanks for your feedback.</value>
      <webElementGuid>00892e07-a225-4996-8645-550fe6cdf391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rn_AnswerFeedback_3_ThanksLabel&quot;)</value>
      <webElementGuid>af0bf344-1210-4a6a-bb37-fd2f51a9f39e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='rn_AnswerFeedback_3_ThanksLabel']</value>
      <webElementGuid>a081bfb6-d471-4ef2-9cb6-ab4175c9b719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rn_AnswerFeedback_3_AnswerFeedbackControl']/div</value>
      <webElementGuid>d5387a44-0d1d-40c7-a44e-59c40859f607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this answer helpful?'])[1]/following::div[1]</value>
      <webElementGuid>d4292114-5328-4838-8560-d1eed90fe8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change settings'])[1]/following::div[4]</value>
      <webElementGuid>3870f0cb-1f54-4284-a07a-0f9a785974a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print Article'])[1]/preceding::div[1]</value>
      <webElementGuid>c34e8b57-18d8-440c-bb06-bfa7e4cc648c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Article Information'])[1]/preceding::div[1]</value>
      <webElementGuid>35aa007b-7b92-42c8-8454-d5a115149bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thanks for your feedback.']/parent::*</value>
      <webElementGuid>b946883f-110d-43d6-9e23-437a15f2a1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>d68fcfc5-289d-4b2b-8844-6cc98193c53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rn_AnswerFeedback_3_ThanksLabel' and (text() = 'Thanks for your feedback.' or . = 'Thanks for your feedback.')]</value>
      <webElementGuid>512edf9e-5a5a-4b1a-a6f5-9a7afbefbceb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
