<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accept</name>
   <tag></tag>
   <elementGuidId>127f587b-95de-4d90-a1d2-c14702d11e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='hs-eu-confirmation-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hs-eu-confirmation-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>28d72c4e-5308-497a-a255-5c27b3d13c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>1e0864b9-9e81-4d58-a61c-1da6e3b04966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hs-eu-confirmation-button</value>
      <webElementGuid>a68248b1-6598-44bb-b391-5ff4a2532d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51b4e746-371a-4d32-a2ca-7145d829a753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Accept
  </value>
      <webElementGuid>891b96eb-d831-4b4f-9020-38b3311eef56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs-eu-confirmation-button&quot;)</value>
      <webElementGuid>4201e81e-9036-42fd-a95c-1baa33e6ac23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='hs-eu-confirmation-button']</value>
      <webElementGuid>c1e8d279-cf3d-4e47-b2fd-2178a52125f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs-eu-cookie-confirmation-button-group']/a</value>
      <webElementGuid>dd291bee-33d2-4e96-8742-39d7be5d14fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Accept')]</value>
      <webElementGuid>0c256cbc-c860-44e0-bf03-6ccb275a3a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[1]/preceding::a[1]</value>
      <webElementGuid>0509838d-4afc-4a5b-959f-6f0eb4fe0b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/preceding::a[3]</value>
      <webElementGuid>33ecb3b7-d440-4ed3-b458-94698524c352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept']/parent::*</value>
      <webElementGuid>3fc834fc-faf5-46a3-992a-fa74fc25a0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>762331ae-6302-496d-aa78-7ae309381817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>bce97e4b-6d14-4d09-8d5d-d522f9f5e293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'hs-eu-confirmation-button' and (text() = '
    Accept
  ' or . = '
    Accept
  ')]</value>
      <webElementGuid>07972ebe-38f8-4501-9d78-3b32d0be12d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
