<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SKIP</name>
   <tag></tag>
   <elementGuidId>0655f356-56ee-4f53-ba2d-15e5fd87b038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continueWavemaker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='continueWavemaker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d620eb3-ef62-4256-b752-b35349314588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right</value>
      <webElementGuid>adf7a03f-aefa-4f34-a48b-e45a1a475657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continueWavemaker</value>
      <webElementGuid>a0ed84a3-2b2b-4dce-9be9-21083b9b6011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SKIP>></value>
      <webElementGuid>a964b06a-a64a-4af0-a6ca-e7f461da693c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continueWavemaker&quot;)</value>
      <webElementGuid>6b296008-fd85-4716-ae35-66f3e42e8eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/WaveMaker/Page_WaveMaker Studio/iframe_WaveMaker_embed-responsive-item iframe-content</value>
      <webElementGuid>52f07585-fc71-4ebd-9d7c-1be1db0eb4a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='continueWavemaker']</value>
      <webElementGuid>f4538944-ffad-48ae-b9f5-ebb1146f3900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SKIP>>')]</value>
      <webElementGuid>26fa953b-8839-4679-aae2-1787fc3fdeb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click &amp; Deploy'])[1]/following::a[3]</value>
      <webElementGuid>6a6e2683-e292-4059-96f7-49b4f30b5efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsive Apps'])[1]/following::a[3]</value>
      <webElementGuid>45b974e8-e1a6-4e4a-a1ec-2376733a6bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'continueWavemaker', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>9eb9dbb8-9f55-418a-9566-ce4ce9afee25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SKIP>>']/parent::*</value>
      <webElementGuid>25a5c3e4-c79c-4577-9800-f81e26454fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/a</value>
      <webElementGuid>c294aac5-752b-4247-8002-0722f0ba2b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'continueWavemaker' and (text() = 'SKIP>>' or . = 'SKIP>>')]</value>
      <webElementGuid>d5812417-cae1-4ae9-ac7c-10df5f61d094</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
