<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Okay, got it</name>
   <tag></tag>
   <elementGuidId>31579237-3489-4fe7-82f8-fb6405745eed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='ng-app']/div/div/div/div/div/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>002565e2-4b56-4fa4-b40d-613762a87713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ng-binding</value>
      <webElementGuid>d7a0dbfd-32b0-43b8-a35a-f71eaaab529f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>closeWMPopup()</value>
      <webElementGuid>af5aacd0-9ed0-42ba-bcf8-f738bf3d1ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Okay, got it</value>
      <webElementGuid>177b54ed-dfb9-437e-93a7-131174866c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ng-app&quot;)/div[@class=&quot;modal wm-studio-dialog wm-beta-version-switch-dialog fade ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal default&quot;]/div[@class=&quot;app-dialog modal-dialog clearfix ng-scope ng-isolate-scope&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;app-dialog-body modal-body&quot;]/div[@class=&quot;details-container ng-scope&quot;]/div[@class=&quot;details&quot;]/div[@class=&quot;actions&quot;]/button[@class=&quot;btn btn-primary ng-binding&quot;]</value>
      <webElementGuid>e4c8f742-eae0-4d8b-a008-6a272d18c68b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='ng-app']/div/div/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>eeebc16e-ed00-4a1f-8f62-c3f661c49ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Information'])[1]/following::button[1]</value>
      <webElementGuid>14ead57f-0260-4beb-b9ee-00c7be28e5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WaveMaker applications now run on Java 11 and are deploy-ready on the latest Tomcat version.'])[1]/following::button[1]</value>
      <webElementGuid>64104faf-0088-4b93-a344-2f8993503ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[1]/preceding::button[1]</value>
      <webElementGuid>4c289038-77ec-418d-b242-dffd7b4d5b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade Now!'])[1]/preceding::button[1]</value>
      <webElementGuid>7c2e34e5-6384-453f-a437-d5069f40d5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Okay, got it']/parent::*</value>
      <webElementGuid>4a1ed86c-fbad-4c63-8788-af850650057c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>92b9d963-621a-4c27-bb7f-23263b83c5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Okay, got it' or . = 'Okay, got it')]</value>
      <webElementGuid>e377f034-1703-4c3b-aba8-efbe09593fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
