<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Delete_enjoyhint_disable_events</name>
   <tag></tag>
   <elementGuidId>e1e33a83-b09a-4f64-8a56-ec8f8d6177a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='ng-app']/div[6]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a10421c0-e235-4229-b523-e9dbd1f39879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enjoyhint_disable_events</value>
      <webElementGuid>df54aebe-d515-4456-8193-a07d7f466df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ng-app&quot;)/div[@class=&quot;enjoyhint enjoyhint-step-8&quot;]/div[@class=&quot;enjoyhint_disable_events&quot;]</value>
      <webElementGuid>74639325-af9c-4afb-83c6-52c915a1a0b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='ng-app']/div[6]/div[6]</value>
      <webElementGuid>4fa59752-ba0a-49ea-85f9-4f6af227fffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[6]</value>
      <webElementGuid>1789bab4-41f5-461d-841c-f679e0eea3a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
