<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NEXT_enjoyhint_close_btn</name>
   <tag></tag>
   <elementGuidId>261585c3-3496-4801-a5fa-94f642dcd483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.enjoyhint_close_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b8a8d40-9aa8-40c4-83ac-03c174ad1036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enjoyhint_close_btn</value>
      <webElementGuid>1343f18c-4357-450a-b558-210e6829cfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ng-app&quot;)/div[@class=&quot;enjoyhint enjoyhint-step-4&quot;]/div[@class=&quot;enjoyhint_close_btn&quot;]</value>
      <webElementGuid>082a3c03-add6-4650-a513-c43f3f502aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='ng-app']/div[6]/div[9]</value>
      <webElementGuid>69be3cc7-b9e5-4d77-afed-8072c4110fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]</value>
      <webElementGuid>35d7dadb-51e9-4edb-ae1e-84324ab881f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
