<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Projects_embed-responsive-item ifram_709343</name>
   <tag></tag>
   <elementGuidId>93a80d39-f709-48b6-82ad-8a0c271fb68a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.embed-responsive-item.iframe-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='integrationIframe']/div/div/div[2]/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>be88136a-3d17-496e-8b7c-dc5d0e5f73e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>embed-responsive-item iframe-content</value>
      <webElementGuid>88558159-7afc-41fe-9345-5d5f59cd73d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>a17f1ad7-3105-4d3c-8c23-3cab257c1a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e72976b9-981e-460b-9340-57a7be914530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a6d0b512-69f4-40a4-b5a1-c58d358dfb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d9ac8ab-f512-4c89-bb30-a381c2aca316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>seamless</name>
      <type>Main</type>
      <value>seamless</value>
      <webElementGuid>c0d02e45-0702-442c-9c96-baf8333d11bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/subscriptions/app/main.html#/congratsdialog</value>
      <webElementGuid>1556deda-6de1-4a68-897e-1714af2abb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;integrationIframe&quot;)/div[@class=&quot;app-dialog modal-dialog app-iframe-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;app-dialog-body modal-body&quot;]/div[@class=&quot;embed-responsive app-iframe ng-isolate-scope&quot;]/iframe[@class=&quot;embed-responsive-item iframe-content&quot;]</value>
      <webElementGuid>9f267006-2ce2-4f7e-99f0-71b2a3c88dfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='integrationIframe']/div/div/div[2]/div/iframe</value>
      <webElementGuid>4126a926-ebd7-4d1e-a82b-807e98ee60da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9ba3283b-a66a-4fcc-835e-2c15950f2382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/subscriptions/app/main.html#/congratsdialog']</value>
      <webElementGuid>0d39ba0c-f1c6-4d9e-a375-f0b290067414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
