<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_WaveMaker_embed-responsive-item iframe-content</name>
   <tag></tag>
   <elementGuidId>39941b77-6cff-4279-91c4-98b607135d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.embed-responsive-item.iframe-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='integrationIframe']/div/div/div[2]/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fa0596bb-ee87-448b-ba6f-d2f8223f9669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>embed-responsive-item iframe-content</value>
      <webElementGuid>527da72e-4bc2-4b57-995f-e520e7f0a82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>dd386966-16e7-40d1-b162-c7e14d1aa2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>22b98f76-2f8d-46ed-9a19-6a275522a597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>67cf4c28-ef66-48d4-86bc-317d08c2043b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a5ef31d2-fecc-446d-9ab3-4e3240a951cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>seamless</name>
      <type>Main</type>
      <value>seamless</value>
      <webElementGuid>704ea764-d8aa-4367-a7fb-667daa42461c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/wavemaker-integration/wmscreens/slideshow.html</value>
      <webElementGuid>07e15781-2be5-4e44-8b6d-ad9701de990a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;integrationIframe&quot;)/div[@class=&quot;app-dialog modal-dialog app-iframe-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;app-dialog-body modal-body&quot;]/div[@class=&quot;embed-responsive app-iframe ng-isolate-scope&quot;]/iframe[@class=&quot;embed-responsive-item iframe-content&quot;]</value>
      <webElementGuid>8e755cd6-3bf4-429b-beec-dea45adf571e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='integrationIframe']/div/div/div[2]/div/iframe</value>
      <webElementGuid>5fbdf73f-41ab-4523-adc8-752df4aeb742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4d564477-6085-4319-a79c-c072b698325e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/wavemaker-integration/wmscreens/slideshow.html']</value>
      <webElementGuid>118bc569-6513-4aea-b5ec-68707d8a5e50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
