<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Obj_ContectInactive</name>
   <tag></tag>
   <elementGuidId>6ef042d1-5978-45c1-b322-e3a680f57814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[data-droptarget-for=&quot;wm_page_content1&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
