<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_CLI Overview and Command Referencelink</name>
   <tag></tag>
   <elementGuidId>27a73f49-a0d6-4b43-8a8f-aacdd63a8eb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cli-overview-and-command-reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='cli-overview-and-command-reference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>cefd1724-e40a-425c-8378-d4c1c225b794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cli-overview-and-command-reference</value>
      <webElementGuid>b611c8ea-957c-4b8a-addf-9848aad6573e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLI Overview and Command Referencelink</value>
      <webElementGuid>bcd5b5d3-68c7-48b1-adb1-3b069cb64509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cli-overview-and-command-reference&quot;)</value>
      <webElementGuid>b4230abb-c48c-4e31-90c1-078fe5edaa32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='cli-overview-and-command-reference']</value>
      <webElementGuid>c9be78f8-7b89-4371-9f77-4701c1124221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='cli']/aio-doc-viewer/div/div[2]/h1</value>
      <webElementGuid>ad3e1733-7820-40cb-a7eb-41ed5ece6d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>fe1b70a6-a3f1-426f-b7f3-8dff9af2e826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'cli-overview-and-command-reference' and (text() = 'CLI Overview and Command Referencelink' or . = 'CLI Overview and Command Referencelink')]</value>
      <webElementGuid>9ccfbe02-37a5-401d-acf2-334f0a6771fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
