<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calendar_month_year</name>
   <tag></tag>
   <elementGuidId>f8d25bdd-1876-4e5b-8f2a-a5d7536fe4cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-calendar-button-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='mat-calendar-button-0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'mat-calendar-button-0' and (text() = 'NOV 2023' or . = 'NOV 2023')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>69dafe64-6c76-4e24-a74a-0d4e11b43644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-calendar-button-0</value>
      <webElementGuid>c4926c3e-904f-4587-84b5-78f4570484e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NOV 2023</value>
      <webElementGuid>aa58d441-1621-4168-9b84-3a8275c30f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-calendar-button-0&quot;)</value>
      <webElementGuid>5c28524a-69ff-4b63-8c74-fbf7d0490835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='mat-calendar-button-0']</value>
      <webElementGuid>65176eaf-2617-458d-934e-30c49afdec8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-calendar[@id='mat-datepicker-1']/mat-calendar-header/div/div/button/span/span</value>
      <webElementGuid>e75ba13a-b7e5-48d5-8776-06316450cd7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button/span/span</value>
      <webElementGuid>0dc9c978-416c-4206-ba4e-9e769ea1341d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'mat-calendar-button-0' and (text() = 'NOV 2023' or . = 'NOV 2023')]</value>
      <webElementGuid>2d28ed39-5aa0-4ba9-b7be-965212e34017</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
