<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deliveries</name>
   <tag></tag>
   <elementGuidId>a7fdd610-22cf-4911-b3f2-1cc020e5463d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-thumbnail/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-thumbnail.md.hydrated > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>185373ed-192a-4494-a905-2b365bb53e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/ACCicons/4.jpg</value>
      <webElementGuid>280e89ac-8b92-4488-bed0-60af2f5fea1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;plt-desktop md hydrated wf-roboto-n4-active wf-active&quot;]/body[@class=&quot;mat-typography&quot;]/hanz-apps-root[1]/hanz-apps-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-container&quot;]/ion-row[@class=&quot;md hydrated&quot;]/ion-col[@class=&quot;md hydrated&quot;]/ion-row[@class=&quot;ng-star-inserted md hydrated&quot;]/ion-col[@class=&quot;mw-300 ng-star-inserted md hydrated&quot;]/ion-item[@class=&quot;tiles item md item-lines-none ion-focusable hydrated item-label&quot;]/ion-thumbnail[@class=&quot;md hydrated&quot;]/img[1]</value>
      <webElementGuid>3fdd3753-21c4-4540-9067-5a913b0a2eb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-thumbnail/img</value>
      <webElementGuid>4b91d32f-5924-45f3-b6f3-6a31d44d8ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/ACCicons/4.jpg']</value>
      <webElementGuid>96d0f7b9-76fa-4169-a5a3-95228ed85e07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
