<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Only Aggregates</name>
   <tag></tag>
   <elementGuidId>1565d61d-aa33-40d7-9e75-ee8cdb7c2521</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e4f7af3-cfbc-4998-be1c-2c5358f71006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c167-18</value>
      <webElementGuid>6556a2cf-1d7b-45a2-8f9b-fe759f15ce38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-switch</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2f00e3b0-7cb6-4be4-a991-6a81ab41faa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-3</value>
      <webElementGuid>e17642fb-dcef-436c-bb8b-dca5475c571a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Only Aggregates</value>
      <webElementGuid>f492ca2d-ae24-468e-8130-4b3d413da3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-3&quot;)</value>
      <webElementGuid>643281a3-d006-41e7-bfdd-1415b9396f34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-3']</value>
      <webElementGuid>83b6a4a9-e3fc-4980-bcf6-0aab7cb122e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='formly_7_select_productType_4']/div/div</value>
      <webElementGuid>f03c9dbc-c5c9-4cae-9c39-0ad02855a743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div</value>
      <webElementGuid>6c5c0a96-7878-42e4-9302-f3e1ed91edac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-3' and (text() = 'Only Aggregates' or . = 'Only Aggregates')]</value>
      <webElementGuid>812722b0-7aef-4054-bbce-0f02264ab7d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
