<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_nopdf ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>b3fd6504-472f-4b85-b578-1232946fbd13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cell-134']/lib-button-renderer/ion-button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.nopdf.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0d78403c-40fa-4fe1-a0ba-b408d4f7a42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nopdf ng-star-inserted</value>
      <webElementGuid>a4a484fc-03c9-4704-8a08-2e4609dee4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cell-134&quot;)/lib-button-renderer[@class=&quot;ng-star-inserted&quot;]/ion-button[@class=&quot;ng-star-inserted ion-color ion-color-primary md button button-clear ion-activatable ion-focusable hydrated&quot;]/img[@class=&quot;nopdf ng-star-inserted&quot;]</value>
      <webElementGuid>9a455de3-b348-4662-9455-9ff5c80dcfa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cell-134']/lib-button-renderer/ion-button/img</value>
      <webElementGuid>73d922b4-e065-48db-aa8f-0be261f291de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lib-button-renderer/ion-button/img</value>
      <webElementGuid>9fa5a779-97da-46a9-94fe-a661649b5b2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
