<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_custom-icon ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>50bf3893-9988-4d16-85ef-b618e5870424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.custom-icon.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a8500fea-9632-4a75-8c56-3c5e92fbec93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-icon ng-star-inserted</value>
      <webElementGuid>7d557fc4-a614-4439-9335-046de2dc9167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/images/pdfNew.png</value>
      <webElementGuid>80e8d184-60e0-4577-9cb7-c2bfbe187937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;plt-desktop md hydrated wf-roboto-n4-active wf-active&quot;]/body[@class=&quot;mat-typography&quot;]/hanz-apps-root[1]/hanz-apps-dispatch-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;customer-container&quot;]/div[@class=&quot;spacing&quot;]/lh-table[1]/ion-row[@class=&quot;md hydrated&quot;]/ion-col[@class=&quot;md hydrated&quot;]/lh-toolbar[@class=&quot;ng-star-inserted&quot;]/div[1]/ion-toolbar[@class=&quot;md in-toolbar hydrated&quot;]/ion-buttons[@class=&quot;buttons-last-slot sc-ion-buttons-md-h sc-ion-buttons-md-s md hydrated&quot;]/div[@class=&quot;ng-star-inserted&quot;]/ion-button[@class=&quot;mat-tooltip-trigger md button button-clear in-toolbar ion-activatable ion-focusable hydrated&quot;]/img[@class=&quot;custom-icon ng-star-inserted&quot;]</value>
      <webElementGuid>b8c90115-3c43-4816-8928-5290f214e4d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-button/img</value>
      <webElementGuid>a48de2e3-ed07-4327-9031-f012b2166413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './assets/images/pdfNew.png']</value>
      <webElementGuid>eb775814-f59f-4325-9860-94b55b432695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
