<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login_button</name>
   <tag></tag>
   <elementGuidId>449f551e-4f9b-4589-b57a-9ffae123735d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@color='primary']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' Login ' or . = ' Login ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ac1760de-9b05-4c7a-b3ad-9d992a175918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>cca43637-c182-4029-83ce-4211770e4ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login </value>
      <webElementGuid>127d76bb-93ee-4819-a646-1de665a1937d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c433-7 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;formHeight ng-star-inserted&quot;]/ion-row[@class=&quot;md hydrated&quot;]/ion-col[@class=&quot;ion-text-center md hydrated&quot;]/button[@class=&quot;mat-focus-indicator m-r w-100 rounded-shape mat-raised-button mat-button-base mat-primary _mat-animation-noopable cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>e794edc7-8c21-4843-9732-4c5ccb8ff318</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/ion-row[2]/ion-col/button/span</value>
      <webElementGuid>3a84a981-1b1b-40e9-8bc1-c7e9432122de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>12526e4b-2ffd-40f3-8176-cb0f379e4ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Login ' or . = ' Login ')]</value>
      <webElementGuid>5458ceaa-efc1-4fc1-8f2d-c8b4d868b0fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
