<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search</name>
   <tag></tag>
   <elementGuidId>b4a9dbd5-35e2-4cb7-8a4e-373828ff4d4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-raised-button.mat-button-base.mat-primary._mat-animation-noopable.ng-star-inserted.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4a548ef6-332b-4093-9607-9bdef8da9d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>70d66714-62ed-454f-9149-6a35e82a1e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>98e3dd13-b2b7-4776-833c-5a49bd1b94b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;plt-desktop md hydrated wf-roboto-n4-active wf-active&quot;]/body[@class=&quot;mat-typography&quot;]/hanz-apps-root[1]/hanz-apps-dispatch-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;customer-container&quot;]/div[@class=&quot;spacing&quot;]/search-filter[1]/div[@class=&quot;searchfilter-outer&quot;]/form[@class=&quot;searchfilter-inner ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;padding-10&quot;]/button[@class=&quot;mat-focus-indicator mat-raised-button mat-button-base mat-primary _mat-animation-noopable ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>f1dcf396-0dc1-49fa-abcd-23ad4bd131e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button/span</value>
      <webElementGuid>7ecb8e30-e360-49ad-85a5-168e52930e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>df010f81-b7d4-4b53-91c4-04106a1318d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
