<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KatalonWebProject</name>
   <tag></tag>
   <elementGuidId>bb448a74-0872-441f-a4a5-05420abb12a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='job_KatalonWebProject']/td[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.jenkins-table__link.model-link.inside > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c309372-e5ee-4379-8671-c204bd41d378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KatalonWebProject</value>
      <webElementGuid>ce22b49a-0bd5-4bf8-954d-85fa006d3d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_KatalonWebProject&quot;)/td[3]/a[@class=&quot;jenkins-table__link model-link inside&quot;]/span[1]</value>
      <webElementGuid>647fea84-f10d-4768-8546-118564f5b313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='job_KatalonWebProject']/td[3]/a/span</value>
      <webElementGuid>f808da31-ca6f-4777-a063-becae11ab6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::span[9]</value>
      <webElementGuid>104233ff-9a7a-469f-a4db-a56ffe5dce9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/preceding::span[1]</value>
      <webElementGuid>9e0aeb2e-d027-4f8d-ad1d-e79299dcbc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#21'])[1]/preceding::span[1]</value>
      <webElementGuid>86f9eac8-3384-496c-ace1-b73bdd6a8c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KatalonWebProject']/parent::*</value>
      <webElementGuid>4cd68049-cec4-42ac-a20b-211f3e59c580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/span</value>
      <webElementGuid>cf2a5020-6f71-4d14-9baf-13d6f8f0553f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KatalonWebProject' or . = 'KatalonWebProject')]</value>
      <webElementGuid>3c371aba-e4f6-4505-88f3-c1152bdd8218</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
