<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KatalonWebProject</name>
   <tag></tag>
   <elementGuidId>bb448a74-0872-441f-a4a5-05420abb12a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'KatalonWebProject' or . = 'KatalonWebProject')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.jenkins-table__link.model-link.inside > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='job_KatalonWebProject']/td[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5ddea851-99e2-47f1-ae63-6dbce5a9dfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KatalonWebProject</value>
      <webElementGuid>d48ab011-0bcd-4aad-9e6d-49596edbc61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_KatalonWebProject&quot;)/td[3]/a[@class=&quot;jenkins-table__link model-link inside&quot;]/span[1]</value>
      <webElementGuid>57935c25-1f81-49e6-902f-d05a4526bed4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='job_KatalonWebProject']/td[3]/a/span</value>
      <webElementGuid>5b7b7111-9bfe-4349-8a92-5781d7fcc871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::span[9]</value>
      <webElementGuid>8be4d195-0f7a-45c2-97b1-2eb3650c60cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/preceding::span[1]</value>
      <webElementGuid>ec5f9045-d382-4aaf-997d-a97e5c0148ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#21'])[1]/preceding::span[1]</value>
      <webElementGuid>47b9df33-6250-48f6-9160-511243475d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KatalonWebProject']/parent::*</value>
      <webElementGuid>4a0b9736-1230-49a7-86d5-be27fd5a5cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/span</value>
      <webElementGuid>6d73e953-651f-4dbc-8502-fcf823432f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KatalonWebProject' or . = 'KatalonWebProject')]</value>
      <webElementGuid>bb5d19f0-a906-44a5-b5df-0d4c9b28eb33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
