<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Buy Now</name>
   <tag></tag>
   <elementGuidId>5ce39dd5-6208-4779-baa4-19e791320b29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardOrderButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cardOrderButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>160fbf88-0f01-4e56-9baa-07277e7c27ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn cc-btn ctracking svelte-1f08s2c</value>
      <webElementGuid>fcff9eda-25e7-41f4-971b-efcf49921057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bd7924d4-4352-45da-bbcd-8ba48fc139a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardOrderButton</value>
      <webElementGuid>69e65d33-2c3f-4e7e-bdff-4ca10594fcb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a39defa-a8e1-4fb0-941b-6089920cfa9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctracking</name>
      <type>Main</type>
      <value>buy-now,56</value>
      <webElementGuid>a88c448f-2835-4b4d-9d1b-951e49f7b301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Buy Now</value>
      <webElementGuid>aee2be9d-836c-4e08-9b04-d20b8f68dc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy Now</value>
      <webElementGuid>09b5e683-edcb-49d7-83a3-510a4da6ff60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardOrderButton&quot;)</value>
      <webElementGuid>11568482-47c2-4745-80d7-2078b042fded</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cardOrderButton']</value>
      <webElementGuid>9979ad35-fb92-4785-a1ce-58a1c78dcb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-checkout']/main/div/div[4]/div/div[2]/div/div[2]/form/div[7]/div/div</value>
      <webElementGuid>6ae7f888-ee13-4203-91b7-28d14db2f2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and Conditions'])[1]/following::div[3]</value>
      <webElementGuid>bf356859-aeb0-4a6d-920d-c02eb2909327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::div[3]</value>
      <webElementGuid>8d0fefc4-3209-4c33-afd7-a920f60b1a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/preceding::div[7]</value>
      <webElementGuid>de789540-9007-4eb6-8a77-00768e295583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[2]/preceding::div[8]</value>
      <webElementGuid>862dd57e-d12c-4474-b59b-900c96bb34af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div</value>
      <webElementGuid>cd4bfd38-593d-4990-b6b9-d66495ae4858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'submit' and @id = 'cardOrderButton' and (text() = 'Buy Now' or . = 'Buy Now')]</value>
      <webElementGuid>245deadb-cb9b-482b-863e-07fbec858d32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
