<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_billingFirstName</name>
   <tag></tag>
   <elementGuidId>8df92fc2-d1d6-46c2-8277-7b549eb68a03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingFirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingFirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>850f8962-45be-4902-af90-50d3f20a0f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5f4d4c2-7b27-4747-bd9a-ba7529468857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingFirstName</value>
      <webElementGuid>0675d113-0414-45f3-acc9-38dadab2d329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctracking svelte-1n6e56b</value>
      <webElementGuid>9ddbc945-856b-4236-a745-06c021aea6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>b3f48f73-d82c-45d1-a73f-b1a4d9b24f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>445c58c6-5dd2-4d5f-9b77-a329f8b4f6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingFirstName</value>
      <webElementGuid>7eaaff5e-1fc4-43ca-adcb-244740e33a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>6c49339d-736d-43f1-ac1a-ac3b124ba631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctracking</name>
      <type>Main</type>
      <value>billing-first-name,56</value>
      <webElementGuid>9b9e4a58-1adc-4c1f-9c85-ec99cdf5cf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-error</name>
      <type>Main</type>
      <value>1020.1</value>
      <webElementGuid>47193614-c7bd-4cab-8d78-fe43112601ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-error</name>
      <type>Main</type>
      <value>1020</value>
      <webElementGuid>a52b37c4-c14b-4e5f-8b33-b39ad3ebea32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingFirstName&quot;)</value>
      <webElementGuid>4ab249f1-5f6a-4fd7-90a1-be1b486c3714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingFirstName']</value>
      <webElementGuid>3b4669d2-06f3-408b-9e0a-4650b3729ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-checkout']/main/div/div[4]/div/div[2]/div/div[2]/form/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>8629431e-8300-417b-8b0c-3e9a9af1a024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>0a0e7371-9920-40db-a98b-60a4f98d4ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'billingFirstName' and @placeholder = ' ' and @name = 'billingFirstName']</value>
      <webElementGuid>bd07b4b8-989d-47f5-a6c0-89b33a7685dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
