<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_billingLastName</name>
   <tag></tag>
   <elementGuidId>db72a638-b0bd-4627-88dc-5a224f60ff15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>762f957a-19dc-46c0-aa06-be499ea79372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32793184-e966-4b99-b0af-1dd94df891ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingLastName</value>
      <webElementGuid>015a54bb-910d-4b43-8fe3-83cd155da61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctracking svelte-1n6e56b</value>
      <webElementGuid>3bced2bd-8e78-4641-b323-d7a1d748d5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>0b8b0203-3ee2-456a-b270-8d9de863064c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e95fa91a-b77f-4f52-a149-7d815a835d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>08e2e0a4-70a8-4205-9532-2870c16162e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingLastName</value>
      <webElementGuid>ec376f17-81da-40cc-911f-68844f112a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctracking</name>
      <type>Main</type>
      <value>billing-last-name,56</value>
      <webElementGuid>1b89f518-4ac4-4ecc-b0e3-57ef1856c326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-error</name>
      <type>Main</type>
      <value>1021.1</value>
      <webElementGuid>ef6b1868-afb0-467d-a556-7446a771001c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-error</name>
      <type>Main</type>
      <value>1021</value>
      <webElementGuid>86449526-64f8-4d38-9e2e-46c993053cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingLastName&quot;)</value>
      <webElementGuid>2c9db8f0-0df9-4c1d-9460-4a338960452b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingLastName']</value>
      <webElementGuid>7a277c61-389c-4a39-a6d2-0bd7470a9a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-checkout']/main/div/div[4]/div/div[2]/div/div[2]/form/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>118a4b18-2266-46f4-ad13-6f1be5413b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/input</value>
      <webElementGuid>007b52fc-611e-47aa-a3de-e9b146169456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'billingLastName' and @placeholder = ' ' and @name = 'billingLastName']</value>
      <webElementGuid>401276e7-a03c-4322-a513-7f3d98f4b471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
