<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_billingZipCode</name>
   <tag></tag>
   <elementGuidId>2eab649b-220f-4afc-8857-1ce10fac1648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingZipCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingZipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ddf344c-875d-4f85-b112-6b1d1878d945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f95273ea-77db-481f-ac4d-b4cc33598c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctracking svelte-1n6e56b</value>
      <webElementGuid>9e5f44e6-9eb2-4c3e-a6e4-1b6c28a54ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>190f8dda-0385-461c-a1e1-ee8ad8832995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingZipCode</value>
      <webElementGuid>87496f1e-8fd1-4cb8-a3c4-7e4ef4d504b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingZipCode</value>
      <webElementGuid>64fbacd2-84e8-4d7c-99d6-b306120a46c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>c933c148-b44f-41f4-92e7-7467eed87efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ef9c77de-259e-4533-979c-f5a7b363b6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b46ef1b1-4fa8-47d1-b9d4-c2e58a3dadd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctracking</name>
      <type>Main</type>
      <value>billing-zip,56</value>
      <webElementGuid>b83081c4-57ed-47b4-a92a-c219a977dac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-error</name>
      <type>Main</type>
      <value>1028.1</value>
      <webElementGuid>b4e46e81-6879-4007-b85a-5fcd0e0c383c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-error</name>
      <type>Main</type>
      <value>1028</value>
      <webElementGuid>fd51c173-2bc7-437e-9d64-e91da90478f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingZipCode&quot;)</value>
      <webElementGuid>d63ca2ea-b6c4-4014-b01d-4e5d590ae19d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingZipCode']</value>
      <webElementGuid>286461f0-00e4-44a4-b569-f8356d70407f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-checkout']/main/div/div[4]/div/div[2]/div/div[2]/form/div[2]/div[4]/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>533f8027-acec-452b-bbb5-34b35ce3688d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>2f27ecd3-5276-4162-b3a7-807a0dd64d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'billingZipCode' and @name = 'billingZipCode' and @placeholder = ' ']</value>
      <webElementGuid>e7299cff-02d8-4de0-bd79-34eef424a1c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
