<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cardCvv</name>
   <tag></tag>
   <elementGuidId>735e8fe7-7039-4f94-9898-8efc5e742c52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardCvv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardCvv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fa44e4b-eef1-484c-a064-1fbaea5bfa78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>afb3730e-fa9d-40c2-afee-aa088a0d89b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>dd070782-000c-4ac1-a8be-5bc292e8943c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardCvv</value>
      <webElementGuid>e3a237d3-9906-45b0-9522-3ef36308f9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>626981be-2068-42d9-b908-cb4f275b6860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctracking svelte-ulucf0</value>
      <webElementGuid>1d3c68ba-5961-46e2-a7ee-c5472acc3fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3d6b33cc-595a-4831-a4b9-5ee7aefcdb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e30e2ce4-9c13-4346-b18c-f4148f3559db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctracking</name>
      <type>Main</type>
      <value>payment-cvv,56</value>
      <webElementGuid>4a66aae3-5533-4dae-b4ee-5c6681064c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-error</name>
      <type>Main</type>
      <value>1009.1</value>
      <webElementGuid>3f123859-0742-4f38-a71e-c00fcecaba10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-error</name>
      <type>Main</type>
      <value>1009</value>
      <webElementGuid>5a608467-2ace-4e60-9dc7-d6b7b32934f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>613af963-8d7b-4221-86c9-9f1da72c4ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardCvv&quot;)</value>
      <webElementGuid>75ab0e2c-59e9-49c1-bd8c-da79c42d1a42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardCvv']</value>
      <webElementGuid>b5dd6353-610f-4e64-be59-b2a1d52db4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-checkout']/main/div/div[4]/div/div[2]/div/div[2]/form/div[4]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>dd0f4391-d7b5-46e9-8a71-e9f91b75972e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>67cb546a-7562-47e8-9932-e83dc5c21df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'cardCvv' and @placeholder = ' ']</value>
      <webElementGuid>ed7416c9-bb31-46a1-8f25-6f0cb69ea390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
