<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_billingAddress1</name>
   <tag></tag>
   <elementGuidId>d57d6356-c751-467d-940e-094c0f851eb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingAddress1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingAddress1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d59a37b-9feb-4a6d-8056-7ffa8f7d06f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>134b1692-0c3c-4193-a9dc-d91210f7514a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctracking svelte-1n6e56b pac-target-input</value>
      <webElementGuid>c6d6a122-73ad-4445-a629-d815b1e63057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>ab3b4e4d-e80e-447f-ab15-b080116e4190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7094aa18-772e-402a-a44b-40edcbcdcb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e69a0830-b928-4120-8673-44732f72fc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingAddress1</value>
      <webElementGuid>9241d9cf-9637-49b3-9aca-737854784bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingAddress1</value>
      <webElementGuid>ebfd0fa8-3677-42ee-8e92-ae0b8f5bee2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctracking</name>
      <type>Main</type>
      <value>billing-street-address-1,56</value>
      <webElementGuid>a5b60f74-e042-41c7-82d6-1a3294f90495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-error</name>
      <type>Main</type>
      <value>1024.1</value>
      <webElementGuid>5b56f95b-5ced-44b5-a2fe-d7fc6d2c9020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-error</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>85a3308f-1381-4039-9861-3933bb1d52cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>94822f7d-6a75-4ba3-bd1e-da98134bc806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingAddress1&quot;)</value>
      <webElementGuid>e078bbe2-82bd-4cea-8bee-96961e0beac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingAddress1']</value>
      <webElementGuid>f36a7823-f4ba-423f-89d3-c02c649da57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-checkout']/main/div/div[4]/div/div[2]/div/div[2]/form/div[2]/div[2]/div/input</value>
      <webElementGuid>4fcd8ff3-8f8f-4ce0-ac42-01b61b2c8f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>fc96f38a-6a28-4b97-9148-1aa59f5fdf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = ' ' and @id = 'billingAddress1' and @name = 'billingAddress1']</value>
      <webElementGuid>acd89adb-deaf-4f97-8eae-42ffce2192cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
