<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apartment, suite, unit (optional)_bil_b6bd4c</name>
   <tag></tag>
   <elementGuidId>c22aaaa4-51e6-4e7d-b27b-1ec40eea763e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7f51dab-4443-4ca6-9834-31d2766b2bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b8a0bf9-89c8-4b6a-824d-f605b008637b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctracking svelte-1n6e56b</value>
      <webElementGuid>31fc2bd7-daf6-40ac-a0c0-01667a2df2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>fd3cbb20-e166-4112-8917-b0d94d594cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>96aeeafb-2419-45ad-8d1d-b0a6c03e0c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>33900f2f-457e-4bb2-a069-178c01385445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingCity</value>
      <webElementGuid>6af677db-95bc-4451-b257-afcc9316bdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingCity</value>
      <webElementGuid>5e49fe7b-b0b3-401e-89fd-c84bcf754744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctracking</name>
      <type>Main</type>
      <value>billing-city,56</value>
      <webElementGuid>87a1d9fb-bf51-452c-ac35-80f0e217eadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-error</name>
      <type>Main</type>
      <value>1026.1</value>
      <webElementGuid>0f70fb14-0f85-4301-9b44-493a62c19af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-error</name>
      <type>Main</type>
      <value>1026</value>
      <webElementGuid>0edcd9ce-05a6-4db4-9c7b-9c26cb5cf4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingCity&quot;)</value>
      <webElementGuid>7b32e963-002f-432e-92d9-6088dc5d7784</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingCity']</value>
      <webElementGuid>02b1d689-a44e-444d-a67e-209b3110efdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-checkout']/main/div/div[4]/div/div[2]/div/div[2]/form/div[2]/div[4]/div/div/div/div/input</value>
      <webElementGuid>ec1f2d1e-1dc6-4181-bb35-2d864de2207b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div/div/div/input</value>
      <webElementGuid>aab1464f-1443-4eaf-bc1e-c5cdd8fe3a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = ' ' and @id = 'billingCity' and @name = 'billingCity']</value>
      <webElementGuid>b51c5363-1848-4cd7-b95e-8079a2a9bd1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
