<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Pore Cleansing Brush</name>
   <tag></tag>
   <elementGuidId>f1c0fc8b-a0e3-439a-9a22-55ed19c1643d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tpc-checkout']/main/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>fc9bb115-cc6c-4f22-a665-4af8e32a0f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pmd m-0 p-l-1 p-r-h svelte-1buoa1v</value>
      <webElementGuid>4c81a6e3-5ce1-4318-bfdd-49b169b7d8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-upc</name>
      <type>Main</type>
      <value>842944102064</value>
      <webElementGuid>4f985339-1c77-4215-88b4-47ed0f850faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pore Cleansing Brush </value>
      <webElementGuid>a41d8433-a379-4131-81b8-1dd5d5c6af72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tpc-checkout&quot;)/main[@class=&quot;svelte-f1zuwp&quot;]/div[@class=&quot;grid-x svelte-1x7jtfy&quot;]/div[@class=&quot;cell pane svelte-1x7jtfy&quot;]/div[@class=&quot;grid-x square svelte-1x7jtfy&quot;]/div[@class=&quot;cell svelte-1x7jtfy&quot;]/div[@class=&quot;grid-x panel m-b-1 svelte-1buoa1v&quot;]/div[@class=&quot;cell align-self-middle svelte-1buoa1v grouped&quot;]/div[@class=&quot;grid-x align-middle item svelte-1buoa1v&quot;]/div[@class=&quot;cell small-6 medium-5 show-for-medium align-self-middle p-l-h svelte-1buoa1v&quot;]/p[@class=&quot;pmd m-0 p-l-1 p-r-h svelte-1buoa1v&quot;]</value>
      <webElementGuid>13cab7c2-6868-4b72-ac07-ee6eb98a2036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-checkout']/main/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/p</value>
      <webElementGuid>769092c8-e248-4d63-9e29-570409829b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='remove'])[1]/following::p[1]</value>
      <webElementGuid>8d2409a5-95f7-4c5b-99a1-5bde8977e7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='®'])[2]/following::p[3]</value>
      <webElementGuid>e14f0c17-366e-4213-a5ff-96ca40b4e693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pore Cleansing Brush'])[2]/preceding::p[1]</value>
      <webElementGuid>1330337b-075c-4ad6-89ae-19c48a460cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/p</value>
      <webElementGuid>1797eefd-35d9-49ce-b4d0-fbd4f3bc1164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Pore Cleansing Brush ' or . = 'Pore Cleansing Brush ')]</value>
      <webElementGuid>ee0c4487-24e7-40ae-9649-20a79401e502</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
