<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Proactiv Mark and Scar Duo  - 90 Day</name>
   <tag></tag>
   <elementGuidId>d185ab51-5e9f-497a-95cc-2c1da0a26a2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.pmd.m-0.p-l-1.p-r-h.svelte-1buoa1v</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tpc-checkout']/main/div/div[2]/div/div[2]/div/div[2]/div/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d21663c4-6546-4714-933c-1c78fc3afb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pmd m-0 p-l-1 p-r-h svelte-1buoa1v</value>
      <webElementGuid>13e47fe7-2a8f-4d43-aacf-f8b8076d184b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-upc</name>
      <type>Main</type>
      <value>PABPP90D8658</value>
      <webElementGuid>94e35f89-d6a1-4543-92ab-59d95aac8e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proactiv+® Mark and Scar Duo  - 90 Day</value>
      <webElementGuid>1d91872c-94cc-4781-b082-128e1b72e86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tpc-checkout&quot;)/main[@class=&quot;svelte-f1zuwp&quot;]/div[@class=&quot;grid-x svelte-1x7jtfy&quot;]/div[@class=&quot;cell pane svelte-1x7jtfy&quot;]/div[@class=&quot;grid-x square svelte-1x7jtfy&quot;]/div[@class=&quot;cell svelte-1x7jtfy&quot;]/div[@class=&quot;grid-x panel m-b-1 svelte-1buoa1v&quot;]/div[@class=&quot;cell align-self-middle svelte-1buoa1v grouped&quot;]/div[@class=&quot;grid-x align-middle item svelte-1buoa1v line-item&quot;]/div[@class=&quot;cell small-6 medium-5 show-for-medium align-self-middle p-l-h svelte-1buoa1v&quot;]/p[@class=&quot;pmd m-0 p-l-1 p-r-h svelte-1buoa1v&quot;]</value>
      <webElementGuid>5c366850-71a3-459a-9b3a-507a15b09af7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-checkout']/main/div/div[2]/div/div[2]/div/div[2]/div/div[2]/p</value>
      <webElementGuid>da7bf382-c846-4c2b-b053-c4048b55e067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your selections'])[1]/following::p[1]</value>
      <webElementGuid>2a902e84-b0b6-448f-8db4-ac08e2952694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order summary'])[1]/following::p[1]</value>
      <webElementGuid>a96110b3-712f-4a1c-91c8-924621213fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/p</value>
      <webElementGuid>45c01ef4-4f08-47b6-86fb-336f3c5647f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Proactiv+® Mark and Scar Duo  - 90 Day' or . = 'Proactiv+® Mark and Scar Duo  - 90 Day')]</value>
      <webElementGuid>cb4e3d74-1c78-427f-b043-2dba6766f686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
