<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_State                               _46cb8f</name>
   <tag></tag>
   <elementGuidId>2657e9d3-1346-4e69-ab71-3f79a0e8c5aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingState</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='billingState']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>546f74fb-fa6a-46fc-a0f2-90cde29949e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctracking svelte-1n6e56b</value>
      <webElementGuid>8bf53a57-05e7-4c92-8202-6dc67610ae3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9bc8f586-4b18-4edf-8b18-3bbb4590cdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>21492714-1e2c-4880-9bf3-ee7a2a9dd7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingState</value>
      <webElementGuid>4648a38a-e9a4-4b98-afb1-b10276158546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingState</value>
      <webElementGuid>220715d4-2627-4368-8724-b21def988e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctracking</name>
      <type>Main</type>
      <value>billing-state-dropdown,56</value>
      <webElementGuid>92bc41d6-ed12-4eec-a790-bb850dbecaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-error</name>
      <type>Main</type>
      <value>1027</value>
      <webElementGuid>9288fe9b-9556-4049-96fa-6e0adfab09ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State 
                                Alabama Alaska American Samoa Arizona Arkansas California Colorado Connecticut Delaware District Of Columbia Florida Federated States Of Micronesia Georgia Guam Hawaii Idaho Illinois Indiana Iowa Kansas Kentucky Louisiana Maine Marshall Islands Maryland Massachusetts Michigan Minnesota Mississippi Missouri Montana Nebraska Nevada New Hampshire New Jersey New Mexico New York North Carolina North Dakota Northern Mariana Islands Ohio Oklahoma Oregon Palau Pennsylvania Puerto Rico Rhode Island South Carolina South Dakota Tennessee Texas United States Minor Outlying Islands Utah Vermont Virgin Islands Virginia Washington West Virginia Wisconsin Wyoming Armed Forces Americas Armed Forces Pacific Armed Forces Others </value>
      <webElementGuid>59a14a66-6c65-4bd2-a9db-8ab7a5faa7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingState&quot;)</value>
      <webElementGuid>10d4da5e-283f-4c30-a1fa-333c5bf102d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='billingState']</value>
      <webElementGuid>f35d5f53-08e1-491e-95da-a7fe4be772ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-checkout']/main/div/div[4]/div/div[2]/div/div[2]/form/div[2]/div[4]/div/div[2]/div/div/div/select</value>
      <webElementGuid>8744eb20-0856-4123-9c80-92e0a35cdbe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
      <webElementGuid>1e98b377-a7fb-4bde-b4ba-41c644301000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apartment, suite, unit (optional)'])[1]/following::select[1]</value>
      <webElementGuid>bfa88c53-5761-4670-aed8-8dca46bd365b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip code'])[1]/preceding::select[1]</value>
      <webElementGuid>5a6e7553-7a6b-4bde-a73e-86fc45a209b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card number'])[1]/preceding::select[1]</value>
      <webElementGuid>1ac22c33-99f4-4bb7-bd7c-96dd3c4f16e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>093e93b4-a5ca-40a0-b1d4-2b68459df4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'billingState' and @name = 'billingState' and (text() = 'State 
                                Alabama Alaska American Samoa Arizona Arkansas California Colorado Connecticut Delaware District Of Columbia Florida Federated States Of Micronesia Georgia Guam Hawaii Idaho Illinois Indiana Iowa Kansas Kentucky Louisiana Maine Marshall Islands Maryland Massachusetts Michigan Minnesota Mississippi Missouri Montana Nebraska Nevada New Hampshire New Jersey New Mexico New York North Carolina North Dakota Northern Mariana Islands Ohio Oklahoma Oregon Palau Pennsylvania Puerto Rico Rhode Island South Carolina South Dakota Tennessee Texas United States Minor Outlying Islands Utah Vermont Virgin Islands Virginia Washington West Virginia Wisconsin Wyoming Armed Forces Americas Armed Forces Pacific Armed Forces Others ' or . = 'State 
                                Alabama Alaska American Samoa Arizona Arkansas California Colorado Connecticut Delaware District Of Columbia Florida Federated States Of Micronesia Georgia Guam Hawaii Idaho Illinois Indiana Iowa Kansas Kentucky Louisiana Maine Marshall Islands Maryland Massachusetts Michigan Minnesota Mississippi Missouri Montana Nebraska Nevada New Hampshire New Jersey New Mexico New York North Carolina North Dakota Northern Mariana Islands Ohio Oklahoma Oregon Palau Pennsylvania Puerto Rico Rhode Island South Carolina South Dakota Tennessee Texas United States Minor Outlying Islands Utah Vermont Virgin Islands Virginia Washington West Virginia Wisconsin Wyoming Armed Forces Americas Armed Forces Pacific Armed Forces Others ')]</value>
      <webElementGuid>02580ebe-aa81-4922-b9d8-901d76993a56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
