<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Zip code_check-mark svelte-1l2t73t</name>
   <tag></tag>
   <elementGuidId>63b295aa-2ee1-47a3-9219-3bf198a164ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.field-box.p-l-h.p-b-1.svelte-1f08s2c > div.svelte-1l2t73t > #checkBoxChanged > span.check-mark.svelte-1l2t73t</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//label[@id='checkBoxChanged']/span)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>63134e45-0e42-4b67-85ed-96856095ad05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-mark svelte-1l2t73t</value>
      <webElementGuid>ad3560ca-65b2-4ee4-9937-d51f3590043b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tpc-checkout&quot;)/main[@class=&quot;svelte-f1zuwp&quot;]/div[@class=&quot;grid-x svelte-1x7jtfy&quot;]/div[@class=&quot;cell pane svelte-1x7jtfy&quot;]/div[@class=&quot;grid-x square svelte-1x7jtfy&quot;]/div[@class=&quot;cell svelte-1x7jtfy&quot;]/div[@class=&quot;grid-x panel svelte-68a4ih&quot;]/div[@class=&quot;cell svelte-68a4ih&quot;]/form[@class=&quot;svelte-1f08s2c&quot;]/div[@class=&quot;field-box p-l-h p-b-1 svelte-1f08s2c&quot;]/div[@class=&quot;svelte-1l2t73t&quot;]/label[@id=&quot;checkBoxChanged&quot;]/span[@class=&quot;check-mark svelte-1l2t73t&quot;]</value>
      <webElementGuid>37ee7a2c-1dd1-4741-87d3-48ab3d997b5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//label[@id='checkBoxChanged']/span)[2]</value>
      <webElementGuid>76aa2846-acb8-4c72-a854-6a581c76007d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label/span</value>
      <webElementGuid>8fca89d4-af10-4e6c-b6f3-c131e9f701bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
