<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2267164</name>
   <tag></tag>
   <elementGuidId>a07734c8-5d70-4a89-bd09-d8e731468fb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.alc-highlighted.svelte-6t615t</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tpc-confirm']/main/div/div/div/div[2]/div/div/p/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>faad64d0-2af5-48d5-8bc7-6d1bcf317c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alc-highlighted svelte-6t615t</value>
      <webElementGuid>36369c13-76ba-412c-80cb-ede8bdcaa85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2267164</value>
      <webElementGuid>ee99a7fd-70e5-43d2-8ddc-fa9901c3addc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tpc-confirm&quot;)/main[@class=&quot;svelte-d8obv1&quot;]/div[@class=&quot;grid-x svelte-d8obv1&quot;]/div[@class=&quot;cell pane svelte-d8obv1&quot;]/div[@class=&quot;grid-x square svelte-d8obv1&quot;]/div[@class=&quot;cell p-t-1 svelte-d8obv1&quot;]/div[@class=&quot;grid-x panel m-b-1 svelte-6t615t&quot;]/div[@class=&quot;cell p-b-h svelte-6t615t&quot;]/p[@class=&quot;p-t-1 p-b-h p-l-h svelte-6t615t&quot;]/span[@class=&quot;alc-highlighted svelte-6t615t&quot;]</value>
      <webElementGuid>f35c1316-7757-4ba7-83cd-4a276f1e5224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-confirm']/main/div/div/div/div[2]/div/div/p/span</value>
      <webElementGuid>475a24b4-81fe-4888-b4a1-45ceb359680f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order summary'])[1]/following::span[1]</value>
      <webElementGuid>8085e2fe-e71c-4dce-bc01-11b20b4758cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testnewtooldemo1@yopmail.com'])[1]/following::span[1]</value>
      <webElementGuid>8a5fea55-36da-45ff-b1f8-7df7a1f5e5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='®'])[1]/preceding::span[1]</value>
      <webElementGuid>76bfc33f-9ae7-4235-9a1f-729cf5784a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STANDARD (4-7 BUSINESS DAYS)'])[1]/preceding::span[1]</value>
      <webElementGuid>0116a7bd-0e37-408d-95dc-175964099bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2267164']/parent::*</value>
      <webElementGuid>31c4765d-4925-4b19-a213-10a345ba51db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p/span</value>
      <webElementGuid>d47a52da-84cb-4967-85cf-1596c2337aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '2267164' or . = '2267164')]</value>
      <webElementGuid>3edc0933-7e65-4bad-8410-a45e9e1927c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
