<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Proactiv Mark and Scar Duo  - 90 Day</name>
   <tag></tag>
   <elementGuidId>7b59803b-1d24-44da-812e-7d90cae05631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong.svelte-1buoa1v</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tpc-checkout']/main/div/div[2]/div/div[2]/div/div[2]/div/div[2]/p/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>40bf78d8-a40f-412b-aa59-e184df29f9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svelte-1buoa1v</value>
      <webElementGuid>2d803d03-afc2-4615-8368-51f298deffb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proactiv+® Mark and Scar Duo  - 90 Day</value>
      <webElementGuid>10474e1c-970c-414f-8cbd-e93aa4b850b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tpc-checkout&quot;)/main[@class=&quot;svelte-f1zuwp&quot;]/div[@class=&quot;grid-x svelte-1x7jtfy&quot;]/div[@class=&quot;cell pane svelte-1x7jtfy&quot;]/div[@class=&quot;grid-x square svelte-1x7jtfy&quot;]/div[@class=&quot;cell svelte-1x7jtfy&quot;]/div[@class=&quot;grid-x panel m-b-1 svelte-1buoa1v&quot;]/div[@class=&quot;cell align-self-middle svelte-1buoa1v grouped&quot;]/div[@class=&quot;grid-x align-middle item svelte-1buoa1v line-item&quot;]/div[@class=&quot;cell small-6 medium-5 show-for-medium align-self-middle p-l-h svelte-1buoa1v&quot;]/p[@class=&quot;pmd m-0 p-l-1 p-r-h svelte-1buoa1v&quot;]/strong[@class=&quot;svelte-1buoa1v&quot;]</value>
      <webElementGuid>908be1db-56ef-4bcc-bef5-8d40ea177895</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tpc-checkout']/main/div/div[2]/div/div[2]/div/div[2]/div/div[2]/p/strong</value>
      <webElementGuid>d0854ae4-847b-472d-8290-033c235abf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your selections'])[1]/following::strong[1]</value>
      <webElementGuid>e5625471-7e4c-424c-a024-b0d2666bfa5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order summary'])[1]/following::strong[1]</value>
      <webElementGuid>697efd87-f844-40be-986d-c3aff159564d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proactiv+']/parent::*</value>
      <webElementGuid>9e1e5f90-cb2d-44f0-9078-341666af0da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>f9e20d9c-3e27-408d-8902-d60b6dc3c783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Proactiv+® Mark and Scar Duo  - 90 Day' or . = 'Proactiv+® Mark and Scar Duo  - 90 Day')]</value>
      <webElementGuid>9204e0e0-65eb-4888-8f65-db8b88547e50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
