<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>area</name>
   <tag></tag>
   <elementGuidId>ddfa3221-1dfe-4008-820b-1be5e2564dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//area[@alt = 'Reptiles' and @href = 'Catalog.action?viewCategory=&amp;categoryId=REPTILES']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>area[alt=&quot;Reptiles&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>area</value>
      <webElementGuid>7aa98fe4-38d2-4683-814b-0b0a2e478e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Reptiles</value>
      <webElementGuid>ed1a1be3-5ec7-4001-a726-48666066b742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>coords</name>
      <type>Main</type>
      <value>140,270,210,340</value>
      <webElementGuid>ea0d6e9b-ae18-4c65-853b-9895238895ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Catalog.action?viewCategory=&amp;categoryId=REPTILES</value>
      <webElementGuid>c798d410-5933-40f8-b26e-55d52152c09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>RECT</value>
      <webElementGuid>d2cc0149-5c5d-474b-8abf-121ec837f5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainImageContent&quot;)/map[1]/area[4]</value>
      <webElementGuid>0f82a7da-0eaf-4d16-954c-abf1676194be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainImageContent']/map/area[4]</value>
      <webElementGuid>187ce15d-30a2-4d2b-98af-bdaf806fb647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//area[4]</value>
      <webElementGuid>2d10b94e-b556-4e68-ac76-25f521fc198e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//area[@alt = 'Reptiles' and @href = 'Catalog.action?viewCategory=&amp;categoryId=REPTILES']</value>
      <webElementGuid>39067b6d-c968-4f02-84b7-609c358198bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
