<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>area</name>
   <tag></tag>
   <elementGuidId>ddfa3221-1dfe-4008-820b-1be5e2564dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainImageContent']/map/area[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>area[alt=&quot;Reptiles&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>area</value>
      <webElementGuid>735be08a-2cd9-4ebf-9222-225536f8adbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Reptiles</value>
      <webElementGuid>60ab8531-0d6c-4ade-ad73-07dd3e9e7002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>coords</name>
      <type>Main</type>
      <value>140,270,210,340</value>
      <webElementGuid>a9a9fba3-629d-4069-869c-5525877e1c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Catalog.action?viewCategory=&amp;categoryId=REPTILES</value>
      <webElementGuid>c7a709b2-b7f5-432d-9b75-c623644665b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>RECT</value>
      <webElementGuid>99fa99c1-a7ea-45e5-8c41-8aad0fa700f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainImageContent&quot;)/map[1]/area[4]</value>
      <webElementGuid>b7aa5fe5-f66b-4569-9fef-fbbe02025a07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainImageContent']/map/area[4]</value>
      <webElementGuid>71864ab4-a33f-4480-8390-42b5d70940d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//area[4]</value>
      <webElementGuid>1e5ebb76-8205-4856-b8e0-52d61e4a9826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//area[@alt = 'Reptiles' and @href = 'Catalog.action?viewCategory=&amp;categoryId=REPTILES']</value>
      <webElementGuid>c0b7cf74-7ed1-4ee4-bf1b-8f7724d25e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
