<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sign In_img_cart</name>
   <tag></tag>
   <elementGuidId>39bbe532-06c6-49d2-aba4-f1a8fc625afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='img_cart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;img_cart&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>003b4563-b2ef-44e9-b483-c8efbfa9d274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>373d4e15-86b1-4a3f-bcd0-7dd8789a81ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>img_cart</value>
      <webElementGuid>b385b4e1-dd45-4d14-aea5-98f5cdac49ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/cart.gif</value>
      <webElementGuid>6534452c-b220-411f-80c5-55e34a5faf14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MenuContent&quot;)/a[1]/img[1]</value>
      <webElementGuid>9f3f0d21-62b6-4984-9f6d-67a0c2a057e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='img_cart']</value>
      <webElementGuid>dd88354a-2891-45c9-b50e-3cd16341e86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MenuContent']/a/img</value>
      <webElementGuid>de257598-b2c3-4cc4-b79e-c782e25d7b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>65647b70-ba93-41f2-9df4-0633b0c40b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'img_cart' and @src = '../images/cart.gif']</value>
      <webElementGuid>29528fc1-09fe-494e-b698-f9e2c5b4d366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
