<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable MyBanner_account.bannerOption</name>
   <tag></tag>
   <elementGuidId>2d0e8dc8-4156-4fa0-ac59-dedf92c89312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='account.bannerOption']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;account.bannerOption&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f4a0ceb-c1b4-433c-9736-8fbb32d4a408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account.bannerOption</value>
      <webElementGuid>5249cb6a-64a3-42bf-8597-56bc53b8a1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b039dcd1-5416-4173-aba8-a0f84822fb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>10193b18-4aa8-4ce2-b1f6-adbdd039d94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[3]/tbody[1]/tr[4]/td[2]/input[1]</value>
      <webElementGuid>5f42ddae-7fc9-4d6a-b52f-49c72cf0c535</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='account.bannerOption']</value>
      <webElementGuid>28abfab9-eff4-4a5a-a25f-11ed0310f2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table[3]/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>dfc1e121-92b4-46c1-bcd7-2180ad80c22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>8dd718a6-77b9-4761-9897-1da08d4e6635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'account.bannerOption' and @type = 'checkbox']</value>
      <webElementGuid>8c230470-7cc4-415b-a840-92fd2edf4a8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
