<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>cc91a9fa-7d0f-4df5-ad36-baaf97b198f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_lbLogin > img1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_cphContent_lbLogin']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>55b19ec8-b141-4c85-9ab0-5e85c84cf7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://onlinetradeb1na.powerbroking2u.com.my/MIBWecos/Images/btn_login.png</value>
      <webElementGuid>d2cad485-67fc-4ed7-aee2-952dcc8f616a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>53b1a84e-342c-41d0-ba1e-715a5ad84cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>87</value>
      <webElementGuid>8ef4f5e7-bf00-4ae1-826c-a0fcdba9e96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>af9ff1ab-0d49-464c-8174-34d0c62c08cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>absmiddle</value>
      <webElementGuid>9cd0b037-e7f1-4765-b871-837cfb4b9670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_lbLogin&quot;)/img[1]</value>
      <webElementGuid>aedd23c8-b495-4cf8-8d8f-2e9e96ea9229</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_cphContent_lbLogin']/img</value>
      <webElementGuid>356f9525-849a-484f-8ec2-13aa7a82c1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://onlinetradeb1na.powerbroking2u.com.my/MIBWecos/Images/btn_login.png')]</value>
      <webElementGuid>8b4d4d1c-3fe8-4c95-ab2e-e80c8b1754cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/a/img</value>
      <webElementGuid>849354e3-60bd-43c7-ac16-574cc6ead829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://onlinetradeb1na.powerbroking2u.com.my/MIBWecos/Images/btn_login.png']</value>
      <webElementGuid>1d1ac092-034b-497f-bdec-78d4ac639a75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
