<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_ctl00cphContenttxtUsrPwd</name>
   <tag></tag>
   <elementGuidId>302d003d-bda4-467f-8b72-71c000a2efb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphContent_txtUsrPwd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_txtUsrPwd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d862fde-e6c0-4118-8c70-304dfe91adf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphContent$txtUsrPwd</value>
      <webElementGuid>50ebd130-4412-4990-887c-e68e18381b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>71711293-fb4c-48f6-9336-610c4794d3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>0ad41bb7-a78c-40fa-89f0-d01fe4099399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphContent_txtUsrPwd</value>
      <webElementGuid>b11d23d0-e245-4be7-ad42-235000696b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textBlack</value>
      <webElementGuid>e373270b-4366-4b2a-9d1c-dc0e0a0614a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dcd594b6-4e14-45d4-bb85-99b1b4c322c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_txtUsrPwd&quot;)</value>
      <webElementGuid>1455567d-cc6a-429a-81b5-e6f6e86a30b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphContent_txtUsrPwd']</value>
      <webElementGuid>0312d6ee-7138-434e-a46d-d9bd02bd51fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblTextbox']/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>c2928ac7-db43-488e-8e39-d4636b64f069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>866cc44c-2203-4488-8358-8c215e999374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cphContent$txtUsrPwd' and @type = 'password' and @id = 'ctl00_cphContent_txtUsrPwd']</value>
      <webElementGuid>62aa1a56-1dbc-4ebd-a6cc-bbdad1787b23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
