<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_ctl00cphContenttxtUsrID</name>
   <tag></tag>
   <elementGuidId>d395c720-12d6-4176-a991-5de33dfae7c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphContent_txtUsrID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_txtUsrID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01e1af02-9788-424d-b431-8430b720cf21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphContent$txtUsrID</value>
      <webElementGuid>8b6019cc-676b-44a6-8568-f23227512d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83f0e293-76b5-4578-848d-f7a3f2ecacea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>c089dcad-2ba5-41d8-9d29-30a0a4a860b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphContent_txtUsrID</value>
      <webElementGuid>09d5ff49-5cdc-4e09-a9d4-cd669cd0b124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textBlack</value>
      <webElementGuid>0ebfc820-83b6-4417-bd2d-5875a5cd5843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_txtUsrID&quot;)</value>
      <webElementGuid>64387971-9495-4781-b35d-bb3f2cf02180</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphContent_txtUsrID']</value>
      <webElementGuid>a72d029e-6751-4d9c-8fb0-06d2d56ac8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblTextbox']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>bd5f77c2-79b7-465a-b516-b807d2e45059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>f35ebae2-bbc4-4c35-a90c-74dfd7e9d6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cphContent$txtUsrID' and @type = 'text' and @id = 'ctl00_cphContent_txtUsrID']</value>
      <webElementGuid>270b8d06-6c00-4f30-af2c-052ddd712a91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
