<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Trade Now</name>
   <tag></tag>
   <elementGuidId>b7f3af54-ae0d-427b-b06d-4d4892782a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_TradeLink > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_TradeLink']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>50b537ae-b8f1-4b60-ae6a-1d4047975271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24079774-59ce-46ae-9979-32254cf247e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webcms/Image/trade.png</value>
      <webElementGuid>5e4b4108-8bf7-4f25-bdec-39ed5717f5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_TradeLink&quot;)/img[1]</value>
      <webElementGuid>916d1411-d52e-4d56-9baf-df3178d1fcfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_TradeLink']/img</value>
      <webElementGuid>18347610-b9b2-4f0c-af5e-8e6f01cc97f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>ca29f56c-e9e3-470a-9f73-0dc9a94e71f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/webcms/Image/trade.png']</value>
      <webElementGuid>0feb9c4f-5d7c-4e12-9777-bce3e9b9839f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
