<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>12189be9-9186-4f94-b595-d92d2383ea2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign-in-submit-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sign-in-submit-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>714fff8f-d414-400c-a763-82bb84fe1b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>467a2cbf-cef0-490a-a585-755dc8021371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7145bb8b-439d-428c-900a-7cff65a3de80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign-in-submit-button</value>
      <webElementGuid>4fb31db3-3644-4509-8424-7bae165fe21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-btn c-btn--primary auth-actions</value>
      <webElementGuid>d3e28e44-fecb-4095-b62c-aa6e0164a765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>785a6545-d62d-4d3a-8771-886bfedddb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-in-submit-button&quot;)</value>
      <webElementGuid>093f79a9-47d9-49e8-b90d-397dd06b5b09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sign-in-submit-button']</value>
      <webElementGuid>c1bc42c2-043a-44d3-bc00-3bff39127acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/button</value>
      <webElementGuid>eae2c845-a132-4bfa-b9a3-e15a50ffed6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>7969b69a-5f1c-4b7b-b937-5c44751cf534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'button' and @type = 'submit' and @id = 'sign-in-submit-button' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>75fa41d3-74ee-44d0-965c-1f3611db169b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
