<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter at least 3 characters_se_f4df24</name>
   <tag></tag>
   <elementGuidId>264501fb-dad6-4dfb-8230-24a10d685dc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.search_input__yIfS8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df66b015-7578-4400-9118-fe25471efd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c8a8cd8-0ec1-4087-ae5a-29d689e3fed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_input__yIfS8</value>
      <webElementGuid>887b58d8-26c6-430c-b7c3-12061e6dad92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search products here...</value>
      <webElementGuid>3207c930-a47c-406b-9987-b3e257b64f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d3579404-cec2-47c1-844b-828191597b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/header[@class=&quot;header_wrap__mGxe1&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;header_nav__jqNm7&quot;]/div[@class=&quot;search_wrap___OBMJ&quot;]/form[@class=&quot;header--search&quot;]/input[@class=&quot;search_input__yIfS8&quot;]</value>
      <webElementGuid>2daa5c37-9091-4ed0-bba7-6931cda86404</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>fdaa57a2-a108-4b48-9326-ef1ddb59cc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div/nav/div/form/input</value>
      <webElementGuid>422dc94d-87db-4a3b-bcf3-002057f4a50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>aabe8adb-66e7-430f-aca8-f22e9ef563e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search products here...']</value>
      <webElementGuid>8e1331ec-deff-4db6-af21-847eacb6e615</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
