<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Download_rte-editable</name>
   <tag></tag>
   <elementGuidId>aa379a62-a103-435b-bb58-9ec3dff18ab8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_editor1']/rte-content/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.rte-editable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1fad1446-9990-4a1b-86db-6a71ffcb30e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rte-editable</value>
      <webElementGuid>8aa41a9f-2f1b-4020-b8d5-41f7926ac974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_editor1&quot;)/rte-content[1]/iframe[@class=&quot;rte-editable&quot;]</value>
      <webElementGuid>45b09d43-3446-4466-97bb-369c95524c72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_editor1']/rte-content/iframe</value>
      <webElementGuid>4babe394-4081-49d0-8be8-78fd3e798ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f7a7c52b-bdc8-4443-897d-876d10b94e27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
