<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yes</name>
   <tag></tag>
   <elementGuidId>1df87674-baf7-4669-9c8f-2f356806f7e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rn_AnswerFeedback_3_RatingYesButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='rn_AnswerFeedback_3_RatingYesButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff56e33f-4e53-495a-9521-5e900144198e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rn_AnswerFeedback_3_RatingYesButton</value>
      <webElementGuid>9fe1d0a4-b454-4868-8e45-5510af07d801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5fdd54a4-b77f-4488-82b4-62a9d07c430f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-success</value>
      <webElementGuid>45773aed-85b8-4ca2-8e88-7fd7849a8ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>81418531-68cc-4828-bd8e-2f28148881ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rn_AnswerFeedback_3_RatingYesButton&quot;)</value>
      <webElementGuid>9653a7e4-3b45-45e5-96d9-11482f3e1afd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='rn_AnswerFeedback_3_RatingYesButton']</value>
      <webElementGuid>497193c0-b24d-4a57-93b5-cd36b892f491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rn_AnswerFeedback_3_RatingButtons']/button</value>
      <webElementGuid>94e38fd3-ba5d-4491-82ed-d78ebd933251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this answer helpful?'])[1]/following::button[1]</value>
      <webElementGuid>8c00d169-e2b5-4be1-b1ac-72faa12913fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change settings'])[1]/following::button[1]</value>
      <webElementGuid>5db72891-3d39-40eb-b32a-60c2d89859ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>c341b42b-8448-414f-a43b-af62c47a590e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print Article'])[1]/preceding::button[2]</value>
      <webElementGuid>1bb9820d-4eee-4174-8f6a-b0c98db3e853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>b4bdf6e6-836f-4ba8-978e-73322a215a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>e3894825-19ce-49e9-a323-dd29d175f1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'rn_AnswerFeedback_3_RatingYesButton' and @type = 'button' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>65e7085f-c420-4ccd-8996-e2fcbf7ca572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
