<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thanks for your feedback</name>
   <tag></tag>
   <elementGuidId>1438c2b9-76d0-44df-9a78-f46262a6e246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rn_AnswerFeedback_3_ThanksLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rn_AnswerFeedback_3_ThanksLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2bdf1f29-25dc-4fb8-b915-7419c86076a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rn_AnswerFeedback_3_ThanksLabel</value>
      <webElementGuid>0a641231-ba86-43d6-8d44-177c4a9ae877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rn_ThanksLabel</value>
      <webElementGuid>75990cc4-7b7f-4276-8a13-1cab132083c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>493d512a-e982-4480-9eb5-554162e2aab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanks for your feedback.</value>
      <webElementGuid>3cb39881-ab58-43ce-98bf-35f447d70bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rn_AnswerFeedback_3_ThanksLabel&quot;)</value>
      <webElementGuid>a9c90828-8f77-494e-b5e6-6c45587cc55c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='rn_AnswerFeedback_3_ThanksLabel']</value>
      <webElementGuid>2c8ddf3c-b641-4dd2-ba0c-fedef3bd3cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rn_AnswerFeedback_3_AnswerFeedbackControl']/div</value>
      <webElementGuid>549051c6-f665-44d3-a5b1-2a389f9142a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this answer helpful?'])[1]/following::div[1]</value>
      <webElementGuid>5349e5f3-99d4-4f2a-8ce9-149bf978e8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change settings'])[1]/following::div[4]</value>
      <webElementGuid>7e390afd-2474-4b98-a7c0-1a0e7e291447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print Article'])[1]/preceding::div[1]</value>
      <webElementGuid>f70fa414-3322-48ce-b8b4-627924a88534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Article Information'])[1]/preceding::div[1]</value>
      <webElementGuid>3d4c4c77-850a-4707-ba49-c21b5f600400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thanks for your feedback.']/parent::*</value>
      <webElementGuid>bf3fa78d-bfa4-4edb-b175-2071ee0b3864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>3e743421-07af-47e7-809e-70710cb366b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rn_AnswerFeedback_3_ThanksLabel' and (text() = 'Thanks for your feedback.' or . = 'Thanks for your feedback.')]</value>
      <webElementGuid>d8def9de-d68d-4608-a615-96c49a1cefbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
