<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_UNIVERGE BLUE CONNECT</name>
   <tag></tag>
   <elementGuidId>9d991ba8-b804-49d5-b240-f22795d2525c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[3]/div/div/div[2]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>0cd08b61-9d7d-4cde-bf92-68069dd27231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>answer.Summary</value>
      <webElementGuid>d838365b-da43-4866-a32a-5c56c8a60d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>f7c9a9e6-cd28-41a1-bfe5-e7619075cfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UNIVERGE BLUE® CONNECT Integration for Zendesk (Admin Guide)</value>
      <webElementGuid>70e05014-980a-43cd-bdae-68021b6a14a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_18_1_6_1685972582339_6&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;container my-4 article-detail&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-article-content&quot;]/h3[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>fde498af-0ba0-4ac5-b9ee-9e341a4d819e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body/div[3]/div/div/div[2]/h3</value>
      <webElementGuid>789865a1-8988-424e-99bb-de3f2a4e6826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more about Intermedia'])[1]/following::h3[1]</value>
      <webElementGuid>721758c7-0df1-4fa3-ad03-3aff3813a853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='日本 (日本語)'])[1]/following::h3[1]</value>
      <webElementGuid>2b28998c-5db8-42df-a386-10d12ca5e8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installation'])[1]/preceding::h3[2]</value>
      <webElementGuid>826d0a3b-33de-4acb-b3f4-4ee82ecd5476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updating Plugin And Settings'])[1]/preceding::h3[2]</value>
      <webElementGuid>09681924-919e-444c-bbfe-b5bb33317fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>f0c054a8-8979-4d39-be8e-a274186a4fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'UNIVERGE BLUE® CONNECT Integration for Zendesk (Admin Guide)' or . = 'UNIVERGE BLUE® CONNECT Integration for Zendesk (Admin Guide)')]</value>
      <webElementGuid>ad7a2efe-875d-45e5-aa12-e8779645dcbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
