<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_get started</name>
   <tag></tag>
   <elementGuidId>646940f2-de74-40c5-a278-7680dd78b7e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/order' and @title = 'get started' and @id = 'control-cta' and (text() = 'get started' or . = 'get started')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#control-cta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='control-cta']) | (//a[@id='zits-lab-cta']) | (//a[@id='asian-girl-cta'])</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>268fd8d6-f254-4a87-b445-4836ccd293d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/order</value>
      <webElementGuid>0aa8932c-4e0a-4b0e-a491-7ff9ea87e3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>get started</value>
      <webElementGuid>2b13ea5f-6b20-4c8d-aba4-e23a3e6d172c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctracking button1</value>
      <webElementGuid>72fc9d62-2fe8-4e2c-adbf-42ba41b9ed89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctracking</name>
      <type>Main</type>
      <value>get-started-three-people-cta,56</value>
      <webElementGuid>757a134b-92e5-4442-96c0-3d259b70f7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>control-cta</value>
      <webElementGuid>1d179c88-6554-4024-aa0d-d96d99ffdf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseenter</name>
      <type>Main</type>
      <value>const element = document.querySelector('.homebannercontainer');element.classList.remove('ctracking');</value>
      <webElementGuid>aedfed9a-3399-4e99-ab7d-35f2400bc397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>const element = document.querySelector('.homebannercontainer');element.classList.add('ctracking');</value>
      <webElementGuid>d2f1dfbf-f599-4bb3-b08d-0a68440ba9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>get started</value>
      <webElementGuid>ed2ad593-639b-4c30-ad6b-b42b8e8ca30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;control-cta&quot;)</value>
      <webElementGuid>e5f168fc-57f1-4032-b097-2bc35c645d71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='control-cta']</value>
      <webElementGuid>35153b69-154e-416c-acb5-76b1d7be54f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='control']/div/div[2]/div/a</value>
      <webElementGuid>3beb976d-12cc-4c1d-8558-4c883f53c32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'get started')]</value>
      <webElementGuid>190990fa-93ee-4880-97fc-3a0f3c82ac20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reveal Your Clear'])[1]/following::a[1]</value>
      <webElementGuid>653c9dde-dd9e-463b-ba7c-c11250b41c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[2]/following::a[2]</value>
      <webElementGuid>d9ef96f3-038d-4d24-8d5c-3c48f6f4ef77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zits Happen'])[1]/preceding::a[1]</value>
      <webElementGuid>66f52308-3f3a-4d24-860f-50d89ff61fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='®'])[1]/preceding::a[1]</value>
      <webElementGuid>98e77584-1e42-4f9b-b74f-33f99386fdb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='get started']/parent::*</value>
      <webElementGuid>ad24a8d9-82bf-4ee3-8977-0c8713d97b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/order')]</value>
      <webElementGuid>9fd24900-20f4-439c-bd88-01cbaaf7c78e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a</value>
      <webElementGuid>b2efdabd-6aa9-49f4-a31e-ee8eb227eaad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/order' and @title = 'get started' and @id = 'control-cta' and (text() = 'get started' or . = 'get started')]</value>
      <webElementGuid>f4753add-f9ac-417d-8557-cd44ab16d09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value></value>
      <webElementGuid>b5df75ca-84e2-4326-ab16-a4c7424f6750</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
