<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accept_1</name>
   <tag></tag>
   <elementGuidId>abeaba43-45c4-41c8-a740-1106da24d324</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptCookie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='acceptCookie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6da54f39-7e1c-4a6d-a3ac-9e455a6b7633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptCookie</value>
      <webElementGuid>f5495c5a-094f-4671-ad5d-d7f45fb9c693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>db03cf0e-765a-45aa-b48f-3106f21bd72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary small</value>
      <webElementGuid>04de5fb9-0ccd-44c6-9ea6-5b0b08627e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>7d44dd7c-3d7f-49bb-9abc-a756048f53d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptCookie&quot;)</value>
      <webElementGuid>36cfb47d-fbea-46fd-9ecb-2cfe2d01e429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='acceptCookie']</value>
      <webElementGuid>2160d3a2-8b0b-42d6-8016-aceb7014daa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookies']/div/div/div[2]/p/a[2]</value>
      <webElementGuid>97e224f8-bf4f-45d4-a6cc-fd77d4e45db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Accept')])[2]</value>
      <webElementGuid>8930336c-8bbd-4289-9979-b12fc3803e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Information'])[1]/following::a[1]</value>
      <webElementGuid>eef70f60-afe0-4e7b-80a4-9295b4b15e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © NEC Corporation of America 2023. All rights reserved.'])[1]/following::a[7]</value>
      <webElementGuid>167bb61f-4887-44b1-af27-f10f1a1cb23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose country or region'])[1]/preceding::a[1]</value>
      <webElementGuid>8e931d92-4132-47ef-b3f6-2551c7573556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/preceding::a[1]</value>
      <webElementGuid>c5bbf93e-e157-4fae-bd0a-d74b5c7eb566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>e8bfb16f-6044-4457-aabd-fdfc6611fa24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/p/a[2]</value>
      <webElementGuid>b6fa779e-bc80-4f67-95f4-20a1b9c534b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'acceptCookie' and @href = '#' and (text() = 'Accept' or . = 'Accept')]</value>
      <webElementGuid>5ac49f9d-b893-49dc-9fbc-ecf779c15dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
