<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back</name>
   <tag></tag>
   <elementGuidId>76d0cadc-254d-4233-b6ae-4713d12405be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.is-drilldown-submenu-parent.is-submenu-item.is-drilldown-submenu-item > ul.menu.vertical.submenu.is-drilldown-submenu.drilldown-submenu-cover-previous.is-active > li.js-drilldown-back > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='responsive-menu']/div/ul/li[2]/ul/li[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb897d77-84cf-43bb-9759-193f914d2afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>68bfe6db-5ee9-4a13-bc23-8c96202ea68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>97a5af72-c4bc-4bc0-917b-113f9af47970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responsive-menu&quot;)/div[@class=&quot;is-drilldown&quot;]/ul[@class=&quot;vertical large-horizontal menu drilldown&quot;]/li[@class=&quot;navigation-list navigation-list__solutions is-drilldown-submenu-parent&quot;]/ul[@class=&quot;menu vertical submenu is-drilldown-submenu drilldown-submenu-cover-previous is-active&quot;]/li[@class=&quot;is-drilldown-submenu-parent is-submenu-item is-drilldown-submenu-item&quot;]/ul[@class=&quot;menu vertical submenu is-drilldown-submenu drilldown-submenu-cover-previous is-active&quot;]/li[@class=&quot;js-drilldown-back&quot;]/a[1]</value>
      <webElementGuid>6614860d-adbd-4106-a967-df78971b55db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responsive-menu']/div/ul/li[2]/ul/li[2]/ul/li/a</value>
      <webElementGuid>87f57daa-3941-426f-b270-1891141d777b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Back')])[6]</value>
      <webElementGuid>5d0c7bf2-f9ee-4faa-b4a9-4f51e4d664c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Essentials'])[1]/following::a[1]</value>
      <webElementGuid>f2737005-42d3-45d9-8eeb-ae83c26e1676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[5]/following::a[2]</value>
      <webElementGuid>4381133f-b707-4e45-bc6a-29fd5ac42345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All-in-one cloud communications for hybrid &amp; remote productivity'])[1]/preceding::a[1]</value>
      <webElementGuid>6515c8e7-7152-422e-9f61-b8efc2c49de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/ul/li/a</value>
      <webElementGuid>59eb946a-58c0-4e10-8d55-1ef4be8be0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Back' or . = 'Back')]</value>
      <webElementGuid>498c1916-72e3-47df-b1b7-20ba1de22a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responsive-menu']/div/ul/li/ul/li[4]/ul/li/a</value>
      <webElementGuid>9c90c5ce-27f9-47b6-9bce-33472b896cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Back')])[4]</value>
      <webElementGuid>2413a23a-1b2f-434f-9477-a9565c6fb218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workspace Management'])[1]/following::a[1]</value>
      <webElementGuid>6e732cd7-d74d-4f2e-94c1-f98b1df959d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API platform integrating UC &amp; contact center into everyday business apps'])[2]/following::a[2]</value>
      <webElementGuid>9a53f093-bb9e-42cb-81ce-82bfa062a538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automated reservation &amp; touchless check-in solutions'])[1]/preceding::a[1]</value>
      <webElementGuid>26bdeb6a-a06a-4e1d-9669-2983ea9d65c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[4]/ul/li/a</value>
      <webElementGuid>36e427d8-c8f1-4c35-8e87-8119fc6e28e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
