<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EXTENDAPI platform integrating UC  contac_9a8313</name>
   <tag></tag>
   <elementGuidId>9d1a1cbc-37af-4768-a8f6-854e47d3371c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='responsive-menu']/div/ul/li/ul/li[3]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>006320d8-0872-4af5-8794-d8d7ce3cc24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cloud-services/extend/</value>
      <webElementGuid>f89fcd8f-d978-4052-9dff-d8c33fd44c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>2a9ba5e8-26b2-4912-85c7-fb0350d90da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EXTENDAPI platform integrating UC &amp; contact center into everyday business apps</value>
      <webElementGuid>f9fd2de1-eb49-4f9f-9933-0d6f066addd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responsive-menu&quot;)/div[@class=&quot;is-drilldown&quot;]/ul[@class=&quot;vertical large-horizontal menu drilldown&quot;]/li[@class=&quot;navigation-list navigation-list__products is-drilldown-submenu-parent&quot;]/ul[@class=&quot;menu vertical submenu is-drilldown-submenu drilldown-submenu-cover-previous is-active&quot;]/li[@class=&quot;is-drilldown-submenu-parent is-submenu-item is-drilldown-submenu-item&quot;]/ul[@class=&quot;menu vertical submenu is-drilldown-submenu drilldown-submenu-cover-previous is-active&quot;]/li[@class=&quot;is-submenu-item is-drilldown-submenu-item&quot;]/a[1]</value>
      <webElementGuid>764db0c2-f057-409f-8210-adcedc9b3bcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responsive-menu']/div/ul/li/ul/li[3]/ul/li[3]/a</value>
      <webElementGuid>f5ff03d9-de4c-48f2-a261-cc3bd47ad7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi-channel cloud-based contact center communications &amp; oversight'])[1]/following::a[1]</value>
      <webElementGuid>9d935476-9ebe-48dd-81ef-8ffb4e77e0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workspace Management'])[1]/preceding::a[1]</value>
      <webElementGuid>179402ca-5616-41b7-819d-fd29fe036e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/cloud-services/extend/')])[2]</value>
      <webElementGuid>fdb3949a-5983-4b18-a703-1a9c97addde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[3]/a</value>
      <webElementGuid>35b4127d-dfc7-46d6-aa28-f89d9f8c55ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cloud-services/extend/' and (text() = 'EXTENDAPI platform integrating UC &amp; contact center into everyday business apps' or . = 'EXTENDAPI platform integrating UC &amp; contact center into everyday business apps')]</value>
      <webElementGuid>0161d81a-73cc-453e-a8c4-7272ce341701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
